### ISSUE TITLE
Skill: Dependency Injection of mocks

### ISSUE THREAD

**Issue by therealplato** [quii/learn-go-with-tests#1]
It's common to test a piece of code that relies on some other type. You can instantiate a "real" version of the dependency and use it in the tests, but that may have costs - it may run slowly, return something different every time, or be complicated to configure. I prefer to use an interface to declare what the dependency does, so I can use a "mock" version of that type in the tests.

Feel free to copy and/or modify http://therealplato.com/posts/soberoctober11/#quick-pattern-dependency-injection . May be worth providing examples both with and without `github.com/stretchr/testify/mock`

**Comment by quii** [comment]
We've got chapters on mocking and DI now, so hurrah!
