### ISSUE TITLE
Chapter about database/sql testing

### ISSUE THREAD

**Issue by S7evinK** [quii/learn-go-with-tests#103]
I'm not quite sure if that's covered in other chapters, but I'm struggling with testing my database/sql stuff.
The mocking and dependency injection chapters were useful, but I'm still lost.

Let's say, that I've got something like that:
```go
type Connection struct {
	*sql.DB
}

func NewDatabaseConnection(host, database, user, password string) (*Connection, error) {
	u := &url.URL{
		Scheme: "sqlserver",
		User:   url.UserPassword(user, password),
		Host:   fmt.Sprintf("%s:%d", host, 1433),
	}

	db, err := sql.Open("mssql", u.String())
	if err != nil {
		log.Fatal("Error opening database connection:", err)
	}

	return &Connection{db}, nil
}
```
How, if it's even needed, should I test that? Or something like a `GetUser` function.
A chapter about that would be awesome =) Maybe, since we've already got a "HTTP server" and "JSON" chapter, a little extension to those?

**Comment by quii** [comment]
It's certainly a good fit for a chapter and i'll add it to the list

FWIW I would not mock the DB layer in these scenarios, i'd write an integration test with a real local DB. 

But I'd design my DB layer to be as "dumb" as I can, try not to encode any business logic in there.

**Comment by djangulo** [comment]
Hi! I've ran into issues regarding the DB state. At first, I mirrored the InMemoryPlayerStore (from the HTTP Server chapter) with an Sqlite implementation (through GORM), I resolved to delete the `test_db.db` file after each test.

Now I've moved it to Postgres and I'm dumbfounded. I've been running into DB state issues with those same integration tests, i.e. POST x3 -- want 3 got 6 (because it still has the state of the previous run).

Is there a way to save the DB state (which should be "fresh install"), run the tests, make assertions, then revert back to that point?

**Comment by quii** [comment]
A few things

1. Awesome you're trying this out. I wish I had the time to do this.
2. I'd expect things like tables, indexes etc to be done programatically by the software that "owns the db". SO that is always reproducible from an empty DB. I like to exercise that with my tests too. This is usually referred to as "db migrations" which you can maybe read more about
3. I cant remember the specifics with postgres but im pretty sure you can do something like setting autocommit to false or manipulating transactions some way so the changes each test make are not permanent. Again requires a bit of googling

**Comment by djangulo** [comment]
OK so I ditched GORM and changed my logic to use "database/sql" with [github.com/lib/pq](https://github.com/lib/pq ).

I then proceeded to create a a wrapper around each integration test, creating a [Postgres Savepoint](https://www.postgresql.org/docs/11/sql-savepoint.html) "manually", to no avail: scores were still accumulating in the database, 3 at a time (for the 3 requests).

```golang
func savepointWrapper(
	t *testing.T,
	store *poker.PostgreSQLPlayerStore,
	name string,
	inner func(t *testing.T),
) {
	tx, err := store.DB.Begin()
	if err != nil {
		t.Fatalf("error: %v", err)
	}
	// Create savepoint
	_, err = tx.Exec(`SAVEPOINT test_savepoint;`)
	if err != nil {
		log.Printf("savepoint error: %v", err)
	}
	// Run test functions
	t.Run(name, inner)
	// Rollback
	_, err = tx.Exec(`ROLLBACK TO SAVEPOINT test_savepoint;`)
	if err != nil {
		log.Printf("rollback error: %v", err)
	}
	// Release savepoint
	_, err = tx.Exec(`RELEASE SAVEPOINT test_savepoint;`)
	if err != nil {
		log.Printf("release error: %v", err)
	}
	// Commit empty transaction
	tx.Rollback() // tx.Commit() had the same outcome
}
```
What managed to get the tests passing was a very inelegant (by my estimate) alternative New() function,
which:

- Connects to the main DB
- Creates a test DB
- Plugs in said test DB for test
- Drops the test DB on the `removeDatabase()` method

```golang
func newTestPostgreSQLPlayerStore(
	host,
	port,
	user,
	pass string,
) (*poker.PostgreSQLPlayerStore, func()) {
	mainConnStr := fmt.Sprintf(
		"user=%s password=%s host=%s port=%s sslmode=disable",
		user, pass, host, port,
	)
	mainDB, err := sql.Open("postgres", mainConnStr)
	if err != nil {
		log.Fatalf("failed to connect database %v", err)
	}
	_, err = mainDB.Exec(`CREATE DATABASE test_database;`)
	if err != nil {
		log.Fatalf("failed to create test database %v", err)
	}

	testConnStr := fmt.Sprintf(
		"user=%s password=%s host=%s port=%s dbname=%s sslmode=disable",
		user,
		pass,
		host,
		port,
		"test_database",
	)
	testDB, errOpenTest := sql.Open("postgres", testConnStr)
	if errOpenTest != nil {
		log.Fatalf("failed to connect to test database %v", errOpenTest)
	}

	_, errCreateTable := testDB.Exec(`
	CREATE TABLE IF NOT EXISTS players (
		id		serial		PRIMARY KEY,
		name	varchar(80)	NOT NULL UNIQUE,
		wins	int			DEFAULT 0
	);
	`)
	if errCreateTable != nil {
		log.Fatalf("failed to create test DB table %v", errCreateTable)
	}

	removeDatabase := func() {
		testDB.Close()
		mainDB.Exec(`DROP DATABASE test_database;`)
		mainDB.Close()
	}

	return &poker.PostgreSQLPlayerStore{testDB}, removeDatabase
}
```

with this wrapper the tests pass (and behave as expected).

For future readers, all the code can be found in [https://github.com/djangulo/go-fast/tree/sql](https://github.com/djangulo/go-fast/tree/sql).

Problems I see with this approach:

- Tests are slower, not by much (it's only 2 tests after all), but if this were a real application with many more tests, it would be aggravating.
- The PostgreSQL user passed into the application needs the `CREATEDB` privileges, test suite would fail without it.

My questions for you:

- How would you DRY this up?
- Any other method or approach you think would be as effective? (I'm willing to write it and try)
- How have you dealt with this issue in a real world application?

P.S. I'd like to help out with the chapter requested by OP (`database/sql`), please let me know any guidelines or directives you may have for me.

Thank you for taking the time to answer and writing this amazing book!

**Comment by howarddo2208** [comment]
Definitely nice if there's a chapter about testing with database

**Comment by quii** [comment]
Latest chapter covers this https://github.com/quii/learn-go-with-tests/blob/main/working-without-mocks.md
