### ISSUE TITLE
Glossary for readers with 'some' but maybe not 'robust' programming experience

### ISSUE THREAD

**Issue by lnryan** [quii/learn-go-with-tests#105]
I'm noticing terminology that your average Junior developer and even many that have come up in a relatively stable, siloed domain  would likely be spotty on. Is it worth a glossary on these or links to definitions? I realize they're not `go` specific...

If it's wanted, I can help with the leg-work

Examples:
- DSL
- Opinionated
- Domain

**Comment by quii** [comment]
This is an interesting issue thanks @lnryan 

I see it as two choices

A. glossary
B. simplifying the source text. 

I suspect a problem with A is that we'll be reproducing content that is out there already (if someone really cares they can google 'DSL') and it becomes another thing to maintain.

I (currently) think B would be a better approach. The source text can survive without mentioning DSLs, it's just i throw that language around as I take it for granted. 

If you can point to specific instances like you have then we can work on simplifying the text.

**Comment by lnryan** [comment]
@quii - I would also lean toward B, but perhaps a happy medium would just be to use a bit of tactical html in the markdown? _If it works, that is_

```
<span title="Domain Specific Language - represents a highly specialized subset of code geared towards a specific type of task">DSL</span> 
```

**Comment by quii** [comment]
Going to close this for now as it's hard to move on with it. If people find specific things which are not clear, then feel free to raise an issue or PR
