### ISSUE TITLE
Iteration Chapter - Benchmarking - Clarification

### ISSUE THREAD

**Issue by lnryan** [quii/learn-go-with-tests#115]
It's not entirely clear here, whether it takes 139 nanoseconds on average or in entirety, it could be deduced from `ns/op` but would not necessarily be obvious to someone new, nor that the `10000000` is the number of executions as opposed to some other stat. 

Might be worth some further explanation?
 
![image](https://user-images.githubusercontent.com/7268332/43166880-ba1e52f8-8f8f-11e8-9990-5ba0ea63e728.png)

For kicks, I tried the following
```
func BenchmarkRepeatFlat(b *testing.B) {
	for i := 0; i < b.N; i++ {
		Repeat("a", 10)
	}
}

func BenchmarkRepeatIncr(b *testing.B) {
	for i := 1; i <= b.N; i++ {
		Repeat("a", i)
	}
}
```

and got 
![image](https://user-images.githubusercontent.com/7268332/43167074-6706786a-8f90-11e8-8821-a2f309cbcd9a.png)

not unsurprising, but ... a lesson in how not to be clever

**Comment by quii** [comment]
Yes I think these clarifications would be good, i did somewhat gloss over it a bit. Do you want to try raising a PR with your suggestions?

**Comment by lnryan** [comment]
Yup. will do.
