### ISSUE TITLE
Shapes chapter:  You can't get the Perimeter of a triangle given base and height

### ISSUE THREAD

**Issue by bootladder** [quii/learn-go-with-tests#132]
Hi, not sure if this qualifies as an issue.  But, I was hoping to see discussion about some things:

- The chapter defines a Shape interface with the Area() method.  If you add another method to the Shape interface, all shapes (ie. rectangle, circle, triangle) have to implement the new method (Perimeter).
- So it makes sense why there are a lot of 1 method interfaces.
```
type Shape interface {
    Area() float64
    Perimeter() float64
}
```
When you go and implement Perimeter for all the shapes, you realize you can't get the perimeter of a triangle with base and height.

I suggest changing the name Triangle to RightTriangle, because the perimeter is defined.  Then the discussion can continue.

**Comment by quii** [comment]
Hi

You're absolutely right re the triangles. I guess I didn't see it bringing too much value to the discussion of the chapter in hand to make it so you could also refactor `Perimeter` into the interface; not that it would be wrong to do so. 

But for the sake of brevity I decided to just do it for `Area`

**Comment by quii** [comment]
Going to close this, as there's not much discussion :)
