### ISSUE TITLE
Time chapter code gets murky around renaming Game to TexasHoldem

### ISSUE THREAD

**Issue by jdsutherland** [quii/learn-go-with-tests#143]
I've been writing code following the text in the `time` chapter and around L772 things seem to go off the rails a bit in terms of what the text mentions and the state of passing code. Around this paragraph: 
> This should just be an exercise in copying the tests from the `CLI_test` into a new set but with less dependencies to set up; so we wont show all the code here ([you can always check the full source here](https://github.com/quii/learn-go-with-tests/tree/master/time)) but here is an example of one of the moved tests for reference.

That's not to say that it's incomprehensible or that the diligent reader can't work it out but it does feel markedly different from the rest of the book up until this point. I realize this is vague - I will attempt to fill in further details if I find the time, but I wanted to flag it before I forget. I think anyone who writes the code themselves while reading will understand what I mean.

The main issue I'm finding is that there is a considerable gap and amount of work to get the tests back to green and it seems like the text chugs through it. It seems like there are too many test changes along with creating new things and moving things while in the red state.

**Comment by quii** [comment]
I think its a fair criticism, if im honest the latest chapters need some work, they are somewhat rushed. 

Will try my best to find some time to fix them, just got a lot on right now

**Comment by jdsutherland** [comment]
I understand. I think there are some minor issues but it's still quite good and well worth reading. My sense after finishing the book is that if one was going to focus on improving one particular area of the text, this is the area most in need.

**Comment by quii** [comment]
Just to be clear, there's at least one more chapter for the "making an application" bit, I just haven't got around to writing it yet. Before I even do that I could probably do with improving some of the previous bits.
