### ISSUE TITLE
PDF is missing illustration

### ISSUE THREAD

**Issue by midnightrun** [quii/learn-go-with-tests#154]
Hi,
I don't know if this is by purpose but the PDF is missing the awesome illustration which the ePub got as a Cover.

Also maybe a tag with the version of release would be a nice feature on a page.

Chéers!

**Comment by quii** [comment]
Yes this is true and not on purpose! 

I don't exactly know how to fix it, i did a quick google for how to make it work with pandoc but not getting much luck. 

Good idea re the release number, would be good to see how to do that.

**Comment by chriscoffee** [comment]
It seems to generate for me, I've included an image below. As for the version number, you could potentially create a template that pandoc uses with `--template` which has `\rfoot{}` or something, then drop the variable in on generation, the same way you're using the `urlcolor` and use some travis environment variables

<img width="937" alt="Screenshot 2019-03-11 00 04 57" src="https://user-images.githubusercontent.com/7100370/54093593-5fe9fd80-4391-11e9-935f-722b7960ca9e.png">

**Comment by quii** [comment]
Ah yes I did do some changes a while back to include the image but haven't closed the ticket as I haven't had time to look at version number stuff just yet :)

**Comment by midnightrun** [comment]
Thanks guys for taking care of my raised issue. Shall I close it?

**Comment by quii** [comment]
If you'd like! Could you raise a separate one for the version number though as I haven't done that yet but seems like a good idea to me

**Comment by midnightrun** [comment]
Over and out.
