### ISSUE TITLE
Context: removing ctx field from SpyStore

### ISSUE THREAD

**Issue by blogscot** [quii/learn-go-with-tests#156]
In the website's Context section, the text states:

> We removed the reference to ctx from the SpyStore's fields because it's no longer interesting to us. 

I searched but I couldn't find the section where ctx was added to SpyStore. 

Also, the subsequent test still checks this field:

```golang
    if store.ctx != request.Context() {
        t.Errorf("store was not passed through a context %v", store.ctx)
    }
```

These lines seem to have been removed from the code file, but are still present in the markdown file.

**Comment by quii** [comment]
Good spot, something has gone wrong here with the writing and refactoring somehow - will try and sort!
