### ISSUE TITLE
clean tmp file should close first

### ISSUE THREAD

**Issue by Donmmi** [quii/learn-go-with-tests#157]
In IO and sorting chapter, create tmp file helper function should close before remove

`func createTempFile(t *testing.T, initialData string) (io.ReadWriteSeeker, func()) {
    t.Helper()

    tmpfile, err := ioutil.TempFile("", "db")

    if err != nil {
        t.Fatalf("could not create temp file %v", err)
    }

    tmpfile.Write([]byte(initialData))

    removeFile := func() {
        **tmpFile.Close()**
        os.Remove(tmpfile.Name())
    }

    return tmpfile, removeFile
}`

[https://github.com/quii/learn-go-with-tests/blob/0e94809c8a308e995d3f5e80ae43587880991700/io/v3/FileSystemStore_test.go#L22](url)

**Comment by quii** [comment]
Good spot, thanks for raising the issue
