### ISSUE TITLE
Integer/Examples line 105 is hard to understand

### ISSUE THREAD

**Issue by peterleegolang** [quii/learn-go-with-tests#176]
This sentence in integer section 'Examples' is hard to understand, need to be rephrased to be clearer.

https://github.com/quii/learn-go-with-tests/blame/master/integers.md#L105

**Comment by quii** [comment]
> Often code examples that can be found outside the codebase, such as a readme file often become out of date and incorrect compared to the actual code because they don't get checked

Is that better @peterleegolang ?
