### ISSUE TITLE
Inconsistent constant name for English prefix 

### ISSUE THREAD

**Issue by vpkopylov** [quii/learn-go-with-tests#180]
In "Hello world" chapter constants for Spanish and French prefixes are named spanishHelloPrefix  and frenchHelloPrefix, but for English it's just [englishPrefix](https://github.com/quii/learn-go-with-tests/blame/master/hello-world/v8/hello.go#L7). Maybe English constant should be called englishHelloPrefix for consistency?

**Comment by quii** [comment]
You're right yes :)

**Comment by vpkopylov** [comment]
I'll fix it if you don't mind :)

**Comment by quii** [comment]
That would be awesome 🎉
