### ISSUE TITLE
Named result parameters

### ISSUE THREAD

**Issue by kunalkapadia** [quii/learn-go-with-tests#19]
@quii Named result parameters are recommended only in certain context. The last refactor in `Hello, World` gives an impression to use named results parameters in general to make the documentation clear. Should we update it to not use named result param since its pretty clear from the function name itself what it is going to return?
If we agree on this, I can raise the PR for same.

Ref: https://github.com/golang/go/wiki/CodeReviewComments#named-result-parameters

**Comment by quii** [comment]
Hey!

Thanks for the feedback. 

I assume you're referring to ` greetingPrefix(language string) (prefix string)` ?

I guess it's a matter of opinion, but given it's a private function it wont appear in documentation anyway. I did find it a useful way of introducing named parameters so I currently have a little reluctance to remove it.

But I can find another scenario I'm sure and you're right we should try and stick to best practice when we can. 

Let me have a little think over it and i'll let you know :)

**Comment by kunalkapadia** [comment]
Yes I was referring to `greetingPrefix(language string) (prefix string)`.

I am going through other exercises and found that same pattern is being followed there too like [Sum](https://github.com/quii/learn-go-with-tests/tree/master/arrays#write-the-minimal-amount-of-code-for-the-test-to-run-and-check-the-failing-test-output-1) for example which'll appear in documentation too.

> Let me have a little think over it and i'll let you know :)
Sure :)

**Comment by quii** [comment]
Hey

Good point about Sum, I can retrospectively put the explanation there. 

So if you want to go for your PR, by all means go for it - it'll be appreciated
