### ISSUE TITLE
Intro to property based tests spends too long on ConvertToArabic

### ISSUE THREAD

**Issue by SpacedMonkeyTCT** [quii/learn-go-with-tests#199]
I really like the repetition of test, write enough, refactor; but I think you spend too much time on ConvertToArabic().

If you were to reverse the ConvertToRoman() algorithm (possibly a lesson here?), giving:
```
func ConvertToArabic(roman string) int {
	var result int

	for _, numeral := range RomanNumerals {
		symbolLength := len(numeral.Symbol)

		for len(roman) >= symbolLength && numeral.Symbol == roman[:symbolLength] {
			result += numeral.Value
			roman = roman[symbolLength:]
		}
	}
	return result
}
```
You could get to the point of the chapter, 'property based tests', much sooner.

**Comment by quii** [comment]
It's a fair point and I think your solution is nice and _probably_ better than what I did. That being said, it's important to me to emphasise the idea of iteratively building the code, even though this case your way would get us there quicker. So I'll think I'll leave it as is, but thanks for raising the issue.

**Comment by SpacedMonkeyTCT** [comment]
I understand.  I really like the emphasis on iteration too.
