### ISSUE TITLE
Skill: Table Driven Tests

### ISSUE THREAD

**Issue by therealplato** [quii/learn-go-with-tests#2]
Go's declarative nature can mean a lot of boilerplate involved in preparing a test. One option is to use the `TestMain` function to set global state used by many tests:
```
var thing Thing
func TestMain(t *testing.M){
  thing = setup()
}
```
Avoid this pattern whenever possible. Global state bugs lead to fear, anger and the dark side.

Another approach is to copy and paste code around many similar top level tests. You have certainty that no variable state is shared between tests, with the drawback of extra maintenance costs:
```
func TestThingDoesXGivenA(t *testing.T) { thing := setup();  ... }
func TestThingDoesXGivenB(t *testing.T) { thing := setup();  ... }
func TestThingDoesYGivenC(t *testing.T) { thing := setup();  ... }
```

**Table driven tests** use a loop to avoid duplicating boilerplate. They can be easier to comprehend and easier to maintain, because there's no duplicates of the lines that assert the behavior:
```
func TestThing(t *testing.T) {
	type testcase struct {
		input, expected string
	}

	testcases := []testcase{
		testcase{
			input:    "a",
			expected: "x",
		},
		testcase{
			input:    "b",
			expected: "x",
		},
		testcase{
			input:    "c",
			expected: "z",
		},
	}
	for _, tc := range testcases {
		t.Run(fmt.Sprintf("%s given %s", tc.expected, tc.input), func(t *testing.T) {
			thing := setup() // or put outside the loop if you're not concerned about shared state
			actual := thing(tc.input)
			if actual != tc.expected {
				t.Fatalf("expected %q got %q", tc.expected, actual)
			}
		})
	}

}

func setup() func(string) string {
	return func(input string) string {
		switch input {
		case "a", "b":
			return "x"
		case "c":
			return "y"
		default:
			return ""
		}
	}
}

```
The `t.Run` method allows you to label tests, like a `describe` block in other languages' tests. `go test -v -run 'TestThing/z_given_c'` lets you run a specific subtest, which can be nice if you don't want to see log output from other tests or subtests.

**Comment by quii** [comment]
Thanks for this

I certainly will be covering things like table driven tests, benchmarks and property-based tests

**Comment by quii** [comment]
Hey @therealplato 

It has taken 20 days to get there, but here is an almost ready-to-go draft

https://github.com/quii/learn-go-with-tests/blob/master/structs/readme.md

Feel free to check it out and let me know what you think

**Comment by therealplato** [comment]
awesome!
