### ISSUE TITLE
Fix PDF generation with SVG

### ISSUE THREAD

**Issue by quii** [quii/learn-go-with-tests#205]
As of 10.0.1 I have disabled PDF generation as the content has changed in a way which currently breaks it. 

- maths chapter added some SVG which doesn't work with the current version of pandoc the build script is using
- tried updating but ended up using a different docker image, but _that_ one didn't have language support for the Chinese characters

**Comment by jizusun** [comment]
Is it possible to leverage the PDF export from GitBook?
https://docs.gitbook.com/features/pdf-export

**Comment by quii** [comment]
> PDF export is available as a beta feature in the business and enterprise plans.

Given I did have it working before the Chinese characters (for free) I am not really willing to reach in to my pocket for that feature. I feel like it _must_ be possible to configure pandoc correctly, although I have failed on multiple attempts so far!

**Comment by DanoKalhor** [comment]
@quii hi, this book is fantastique, I like to print it .any news to resume pdf release ?

**Comment by filip-dahlberg** [comment]
I would also be interested in the PDF version. Thanks for all the good work.

**Comment by uppalabharath** [comment]
@filip-dahlberg , @DanoKalhor , @jizusun 
I made some fixes and generated the PDF file and attaching it here. Please review
[learn-go-with-tests.pdf](https://github.com/quii/learn-go-with-tests/files/7548778/learn-go-with-tests.pdf)
cc @quii

**Comment by uppalabharath** [comment]
@quii I think we can mark this issue closed now. Please let me know if there is anything pending regarding this
