### ISSUE TITLE
Maths - division by zero

### ISSUE THREAD

**Issue by Jragon** [quii/learn-go-with-tests#218]
Hi there,

In the maths chapter the secondsInRadians can divide by zero: 
```go
func secondsinradians(t time.time) float64 {
    return (math.Pi / (30 / (float64(t.Second()))))
}
```

Turns out you cannot do `10.0 / 0.0` as the compiler will throw a div by zero error, but if you have:
```go
func main() {
  fmt.Println(10.0/zero())
}

func zero() float64 {
  return 0.0
}
```

You get +Inf instead of a runtime error. I guess dividing by +Inf gives you zero, as the secondsInRads function works fine. This is kind of confusing though - might be worth mentioning in the chapter around that point. I would have expected a runtime error

**Comment by quii** [comment]
@gypsydave5

**Comment by gypsydave5** [comment]
Interesting corner case - that's a behaviour I've not seen in Go!

If you fancy putting together a PR @Jragon, I'd appreciate it. Otherwise the world will have to put up with more of my writing...

**Comment by quii** [comment]
@Jragon @gypsydave5 Long time no see!

I've given this a go myself https://github.com/quii/learn-go-with-tests/commit/328438505afc48bcec5503b540335c5ee9500fef

**Comment by gypsydave5** [comment]
Nice. Maybe add something to the effect of "and so we're OK - by some miracle".
