### ISSUE TITLE
Automated check of snippets in the readme files

### ISSUE THREAD

**Issue by quii** [quii/learn-go-with-tests#22]
I have made dozens of mistakes when changing the snippets of Go code in the readme files

Whilst the `build.sh` will check all of the code examples, it cant check the contents of the markdown files

So it's all manual checking and i am rubbish at that.

There has to be a way to automate it

**Comment by damianoneill** [comment]
Possible look at a markdown pre processor like this https://github.com/BurdetteLamar/markdown_helper rather than checking markdown content, it uses the code examples to generate the markdown content.
