### ISSUE TITLE
Suggestion - use snitch for monitoring tests while exploring the book

### ISSUE THREAD

**Issue by axcdnt** [quii/learn-go-with-tests#222]
First, this is an amazing book! Well written, concise and complete. Keep it up!

My two cents is just a suggestion, maybe on the README.md, to add [snitch](https://github.com/axcdnt/snitch) (a tool I created 😛) as a companion tool, so readers can have a constant feedback while _TDDing_ with the book.

Let me know what you think and thank you!

**Comment by quii** [comment]
Your tool looks nice but it wont fit in to everyone's workflow (for instance I like to run my tests through my IDE). Plus I am quite reluctant to add too much about 3rd party tools to this book (I'm already a bit uneasy about chapter 0 in this respect). Thanks anyway :)
