### ISSUE TITLE
Include instructions on using Delve debugger to step through code

### ISSUE THREAD

**Issue by ericksoen** [quii/learn-go-with-tests#223]
I came across this resource yesterday and like this strategy for learning a new language. The [Install Go section](https://github.com/quii/learn-go-with-tests/blob/master/install-go.md) briefly mentions that you can configure Delve with the VS Code extension, but doesn't provide any additional details on how to use it.

Would you be open for a PR that includes some additional information on setting up that extension, as well as how to use it in one of the next lessons (maybe one of the failing tests in the Hello World section?) I'm happy to contribute if that seems like a valuable addition.

**Comment by quii** [comment]
Go for it! The setup was actually contributed by someone else, I'm not very experienced with vs code; I'm a goland user myself. I'd be a bit reluctant to include editor specific instructions outside the setup chapter though,
