### ISSUE TITLE
Import into GitBook

### ISSUE THREAD

**Issue by guylyons** [quii/learn-go-with-tests#23]
Any interest in editing/maintaining this is something like GitBook?

**Comment by quii** [comment]
I'm not _against_ it, but sell the idea to me :) What will be the benefits and what's the effort involved?

**Comment by guylyons** [comment]
The effort should be minimal, since you can import an entire repo. My main interest for this came from reading the Redux docs. Reading on GitBook is easier to navigate and creates a TOC for you. But it may not be necessary-- my thought was, as this grew larger, it could make maintaining among many editors easier.

I could  import my fork to show as an example. :)

**Comment by quii** [comment]
That'd be great! 

When you import, is it possible (well, easy) to automate? If we can make it so it happens as part of the travis build then that would be super.

**Comment by guylyons** [comment]
https://guylyons.gitbooks.io/learn-go-with-tests/content

Here's a really quick and dirty example. It'll format the Markdown a bit, so will prob see some changes in commits with spacing and extra end of line stuff added.

I also notice that the links to the sections would be in need of change, but take a peak. This honestly comes down to a preference sort of thing.

**Comment by quii** [comment]
I will definitely give this a crack over the weekend. 

_At some point_ i hope to output epub, pdf etc as part of the build but i figured I'd try and get some decent content written first rather than all the fun stuff ;)

**Comment by quii** [comment]
This looks good, I will try and integrate this in this afternoon.

**Comment by quii** [comment]
@guylyons @damianoneill are you two on twitter? i want to tweet about this and give a shout-out to you both :)

**Comment by damianoneill** [comment]
Sorry Chris to old :-) 

If you going to use the travis / docker stuff I put in place for the MR's I've just updated to use Docker Volumes rather than ADD.  This allows the image to be used locally (for serving gitbook) when working on an update.

**Comment by guylyons** [comment]
I'm @yugsnoyl, Chris :)

Great work on configuration for this @damianoneill ! Really love the setup.
