### ISSUE TITLE
Include Test Resources

### ISSUE THREAD

**Issue by wagnerjt** [quii/learn-go-with-tests#232]
Running through the gitbook, I noticed there were some really useful Test resources embedded in the chapter itself. For example: benchmarking, code coverage, doc cli, and the `errfmt` package.

I was wondering if we could create a new high level Resource, similar to `GO FUNDAMENTALS`, `BUILD AN APPLICATION`, and `META` , that included examples of these directly. It would be really useful reference to bounce back to.

**Comment by quii** [comment]
While I think these things would be useful, I'm not sure if it's in theme with the book. This book isn't meant to be a direct reference for Go; there's plenty of resources out there on google for that. It's more of a guide of how to learn TDD and Go at the same time through a number of tutorials.
