### ISSUE TITLE
error

### ISSUE THREAD

**Issue by DreaMer963** [quii/learn-go-with-tests#235]
There is an error in Maps in the Chinese version. It was changed in the english version.
![image](https://user-images.githubusercontent.com/41979257/64248892-f401df80-cf44-11e9-8db6-28f745816660.png)

lack **var** keywords.

**Comment by quii** [comment]
I'm not a maintainer of the Chinese version, probably best to get in touch with them https://github.com/studygolang/learn-go-with-tests
