### ISSUE TITLE
My `godoc` executable is missing

### ISSUE THREAD

**Issue by narze** [quii/learn-go-with-tests#248]
I'm quite new to golang. (Thanks for this awesome tutorial anyway because I love TDD ❤️)
I'm not sure that installing go from other source than the official way is including `godoc` or not (I use [asdf](https://github.com/asdf-vm/asdf) though.)

Maybe on the first or second time mentioning `godoc` in Hello world & integer chapter. Can you make a note about installing it from `go get`? I can open a PR if you want.

**Comment by gonzaloserrano** [comment]
Related https://golang.org/doc/go1.13#godoc

**Comment by narze** [comment]
I see, so that on 1.13 onward godoc will have to be installed separately. I'll open a PR

**Comment by tpaschalis** [comment]
Are you still on it @narze, or can I draft something related to this?
