### ISSUE TITLE
Mention Go Modules.

### ISSUE THREAD

**Issue by tpaschalis** [quii/learn-go-with-tests#252]
I like your approach on the "Install Go" chapter, and "Go Environment" section and agree that for beginners, setting a `$GOPATH` and working in these specific directories is more straightforward.

Do you think that the chapter should at least mention Go Modules?   
I could draft a PR for you to look into.

**Comment by quii** [comment]
As shameful as it is to say but right now I'm not writing a lot of Go so I dont have much exposure to modules. If you think it would be a useful addition then please do make a PR :)

**Comment by tpaschalis** [comment]
Okay, I'm on it!
