### ISSUE TITLE
I would like to translate this into Korean.

### ISSUE THREAD

**Issue by cfr2ak** [quii/learn-go-with-tests#253]
# The reason of this suggestion
I'm a big fan of TDD discipline and I found that this resource is extremely helpful for someone willing to learn TDD and Golang at the same time.

Most of Korean programmers can read English. But still, someone starts to program early in their life suffers from the lack of learning resource or lack of their English skills to read resources like this. This is the reason why I want to translate this. 
**I want to make this resource accessible to the people who learns to program in S.Korea at their middle or high school age which is in lack of English skills yet.**

# How much it'll take
I'm university student with part-time job. Therefore I can't make a commitment to do it in a month or two. But if you gives me a permission to do this work with my friends who works in IT firms in S.Korea and makes the process faster, it might can be done within 3 month for sure. If I happen to handle this issue alone, then It would take at best 2 months, at average 4 months, at worst 1 year.

# How I think to do it (If you permit)
If I can, I want to translate part by part and upload to somewhere in your site with multi-language support or separate gitbook page. I read #73 which suggesting to translate this resources into Chinese. I think I can take same approach to fork this repository too. But I'm prefer to do work in an incremental way rather than cathedral way like many other TDD forks. So, I want to take a different approach if I can, rather than fork the whole repository and translate all of them at once.

**Comment by larien** [comment]
Hey! As a Brazilian Portuguese translator, I absolutely encourage you on this. I'm also a university student that works full time. Have you thought on the option of opening it to the open source community? Many of my Brazilian fellas are helping the translation to be better and faster.
Good luck and congratulations for the attitude!

**Comment by quii** [comment]
I welcome you to translate it and am flattered that you want to do it. 

Honestly you can approach it however you like. Please take inspiration from the Chinese and Portuguese translations. They both just forked the project and then translated  when they had time. 

The only thing I ask is you keep attribution to me and link back to the English project. 

Good luck, and let me know if you need any help

**Comment by cfr2ak** [comment]
@larien
Thank you for your sincere advice. I'm quite new to open source community but I would like to give it a shot.

@quii 
Thank you to let me contribute something to this amazing work. I said that I want to take a different approach above, but I concluded that it is better to keep consistency in your document with Chinese and Portuguese translation.
 
So, I would like to fork your repository somewhere and start to work, but publish it on gitbook from the early stage of translation and keep improving it.

I just found LICENSE.md in this repository does not contain your name and year for copyright, I think I cannot copy and use it to clarify that the copyright is on you. Is there any rule for this specification?

Thank you again, and I'll start to translate this weekend if you're okay.

**Comment by cfr2ak** [comment]
I forked it on [here](https://github.com/Gunforge/learn-go-with-tests) and published it on [here](https://gun-yoon.gitbook.io/learn-go-with-tests/). And I just got a commitment from my friend to do revision for my translation so the work may precede faster than my expectation.

**Comment by quii** [comment]
Hey @cfr2ak I am going to close this issue for now. If you've made enough progress I'm happy for you to raise a PR to include a link to your work and I'll merge it in.
