### ISSUE TITLE
goroutine leak in the "select" chapter 

### ISSUE THREAD

**Issue by marco-m** [quii/learn-go-with-tests#257]
Hello,

in the [select chapter](https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/select), the `ping` function

```go
func ping(url string) chan bool {
    ch := make(chan bool)                 // <==== HERE
    go func() {
        http.Get(url)
        ch <- true
    }()
    return ch
}
```

introduces 1 or 2 goroutine leaks (depending on when the timeout expires) when used in the `select` statement in `Racer`:

```go
func Racer(a, b string, timeout time.Duration) (winner string, error error) {
    select {
    case <-ping(a):
        return a, nil
    case <-ping(b):
        return b, nil
    case <-time.After(timeout):
        return "", fmt.Errorf("timed out waiting for %s and %s", a, b)
    }
}
```

The fix is to follow the approach used by `time.After`, which has a channel with buffer length 1.

The code below (self-contained, ready to run) shows how to reproduce:

```go
// https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/select
package main

import (
	"flag"
	"fmt"
	"net/http"
	"net/http/httptest"
	"runtime"
	"time"
)

// FIXME as-it, it leaks:
// - one of the ping goroutines, if the timeout expires after
// - both the ping goroutines, if the timeout expires before
func Racer(a, b string, timeout time.Duration, chBufLen int) (string, error) {
	select {
	case <-ping(a, chBufLen):
		return a, nil
	case <-ping(b, chBufLen):
		return b, nil
	case <-time.After(timeout):
		return "", fmt.Errorf("timed out (%v) waiting for %v and %v", timeout, a, b)
	}
}

func ping(URL string, chBufLen int) chan struct{} {
	// The fix is to add a buffer of 1 to the channel (as for example is done by time.After)
	ch := make(chan struct{}, chBufLen)
	go func() {
		http.Get(URL)
		ch <- struct{}{}
	}()
	return ch
}

func main() {
	var chBufLen = flag.Int("chbuflen", 0, "Ping channel buffer lenght")
	flag.Parse()

	server := newDelayedServer(10 * time.Millisecond)
	defer server.Close()

	for {
		fmt.Printf("%v\n", runtime.NumGoroutine())
		Racer(server.URL, server.URL, 1000*time.Millisecond, *chBufLen)
		time.Sleep(500 * time.Millisecond)
	}
}

func newDelayedServer(delay time.Duration) *httptest.Server {
	return httptest.NewServer(http.HandlerFunc(
		func(w http.ResponseWriter, r *http.Request) {
			time.Sleep(delay)
			w.WriteHeader(http.StatusOK)
		}))
}
```

Example output:

```console
$ ./webrace
2
9
10
11
12
13
14
...

$ ./webrace -chbuflen 1
2
8
8
8
8
8
...
```

**Comment by zachgersh** [comment]
Hey @marco-m - seems like your issue go sorted out with this fix here:
https://github.com/quii/learn-go-with-tests/commit/177d13f3a6ea7fa51f6b2d26577e1f7e7d887c95

I ran your example with the change and now no longer see a leak.

Would you like to confirm as well? Thanks for reporting this!

**Comment by marco-m** [comment]
Hello @zachgersh, let me check.
For the time being I had a quick look at https://github.com/quii/learn-go-with-tests/commit/177d13f3a6ea7fa51f6b2d26577e1f7e7d887c95.  I have the feeling that that commit fixes another leak, because that commit has been merged on May 2019 while I reported this problem in October 2019.

**Comment by marco-m** [comment]
I just checked: the text in the select chapter at the URL https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/select still has a ping implementation without a close():

```go
func ping(url string) chan bool {
    ch := make(chan bool)
    go func() {
        http.Get(url)
        ch <- true
    }()
    return ch
}
```

Am I looking at a wrong URL, or maybe the site is not refreshed from the code?

**Comment by zachgersh** [comment]
@marco-m - yeah, you nailed it, it looks like it was changed in the code examples but never updated in the actual book itself. I will make a PR to update the book code with a close.

**Comment by zachgersh** [comment]
@marco-m you want to review that open PR if you have time 💃

**Comment by denisbrodbeck** [comment]
@zachgersh Maybe that would be a great (advanced) topic on itself. An explanation when and why such goroutine leaks happen and how to avoid those traps absolutely all go beginners fall into.
