### ISSUE TITLE
Question recommended setup for working through this

### ISSUE THREAD

**Issue by damianoneill** [quii/learn-go-with-tests#29]
I created a folder and started working through the code examples.  

I got to here https://github.com/quii/learn-go-with-tests/tree/master/integers#examples 

And realised that godoc wont work for this example as the code is outside of the GOPATH. 

Is there a recommendation on how you should setup your project / directory structure / location that will work with the tutorial?  

Thanks,
Damian.

**Comment by quii** [comment]
Hey

It's on the todo list as chapter zero. Just need to find the time :) 

https://github.com/quii/learn-go-with-tests/blob/master/readme.md#go-fundamentals

In short, you'll be wanting to run this code in something like `$GOPATH/src/github.com/damianoneill/learn-go-with-tests` Then the go doc _should_ work. 

Cheers, Chris

**Comment by damianoneill** [comment]
Thanks Chris for the quick response.  I guess it was more a question around the structure of the repo.  Ideally I'd like to go get github.com/quii/learn-go-with-tests since you have all the code in the repo, obviously this will fail as there is no go code at this level.  I guess there would also be issues since there are overlapping functions / packages based on the v1, v2, v3 approach?  

This approach to teaching go is great.  I'm working through this with a view to using it with my work colleagues.  Looking to get a feel for how I should approach the project setup. 

Damian.

**Comment by quii** [comment]
Thanks for the kind words, and it is a fair criticism of not being able to check it out and then go doc. I guess it's a side-effect of it being a writing thing first. I will have a think about how to make this aspect a little more accessible.

**Comment by damianoneill** [comment]
Thanks Chris, I guess theres a variety of ways of showing the evolution of a piece of code, versioning as you've done, branches or tags.  For the latter this probably will complicate your travis builds but you can do selections on both.  I noted the issue on gitbook request, perhaps any rework could be consider in conjunction with this?

**Comment by damianoneill** [comment]
Chris / @guylyons if you had a repo that looked like this and used git tags and or branches to show partially completed code 

```
├── .travis.yml
├── integers
│   ├── adder.go
│   ├── adder_test.go
│   └── readme.md
├── iteration
│   ├── readme.md
│   ├── repeat.go
│   └── repeat_test.go
├── main.go
└── readme.md
...
```

Would this give you the navigation that you need for gitbook?

**Comment by quii** [comment]
No idea :) 

I will try and find time this weekend to look into the gitbook stuff. As I mentioned in the other issue though I want it to be fully automated or not at all. As in when a new commit to master arrives a new version of the book is made.

**Comment by damianoneill** [comment]
Makes sense.  I think an interesting option might be having your markdown code snippets in the go playground and having them linked, that way those not wanting to work through the examples manually in their environment can click the link and go and test what it does, it also means you will have a way of validating that your snippets are syntactically correct.

**Comment by guylyons** [comment]
@damianoneill you could organize it like that. I'd suggest looking at the [Redux docs](https://github.com/reactjs/redux/tree/master/docs), though. The whole Gitbook thing is more for ease of editing than anything else.

But as far as how to use the tutorial, my personal pref is to create my own repo where I store my code as I go. I rarely clone/edit code direct from tutorials like these unless I notice something broken.

**Comment by quii** [comment]
Whilst I have not set up the being able to check out the code and run it _easily_ the gitbook of this stuff is done i think

https://quii.gitbook.io/learn-go-with-tests/

So closing. Thanks again both
