### ISSUE TITLE
Inconsistency in Maps chapter

### ISSUE THREAD

**Issue by enolgor** [quii/learn-go-with-tests#290]
If you follow the maps chapter, there is a point where you are stuck in an error not addressed in the tutorial.
After you write the TestAdd test the second time: https://github.com/quii/learn-go-with-tests/blob/master/maps.md#write-the-test-first-3

this test checks if an existing word is being added again, if it is a new word it should return a nil error, in order to check that the following call to an assertion function is made: 
```
assertError(t, err, nil)
```

That function is previously written as:
```
func assertError(t *testing.T, got, want error) {
    t.Helper()

    if got == nil {
        t.Fatal("expected to get an error.")
    }
    
    if got != want {
        t.Errorf("got error %q want %q", got, want)
    }
}
```
which will always throw a fatal error since we are passing nil as the `got` parameter.

**Comment by Fauxsys** [comment]
This was also reported in #308 and resolved in commit a8c8a6621c303035068e85e1e8d70013f1108dbc.

@quii, you can close this issue.
