### ISSUE TITLE
Intro to Property Tests error with romanNumarals.ValueOf method signature

### ISSUE THREAD

**Issue by jwp23** [quii/learn-go-with-tests#298]
The issue I have is with the code sample at this step in the Roman Numerals kata https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/roman-numerals#write-enough-code-to-make-it-pass-7.

I have
```go
type RomanNumeral struct {
	Value  int
	Symbol string
}

type RomanNumerals []RomanNumeral

func (r RomanNumerals) ValueOf(symbol string) int {
	for _, s := range r {
		if s.Symbol == symbol {
			return s.Value
		}
	}

	return 0
}

...
//later
func ConvertToArabic(roman string) int {
	total := 0

	for i := 0; i < len(roman); i++ {
		symbol := roman[i]

		if i+1 < len(roman) && symbol == 'I' {
			nextSymbol := roman[i]

			potentialNumber := string([]byte{symbol, nextSymbol})

			value := RomanNumerals.ValueOf(potentialNumber)

			if value != 0 {
				total += value
				i++
			} else {
				total++
			}
		} else {
			total++
		}
	}

	return total
}
```

I get an error that
```
not enough arguments in call to method expression RomanNumerals.ValueOf
        have (string)
        want (RomanNumerals, string)
```
Why does the `RomanNumberals.ValueOf` method require a `RomanNumerals` as the first argument?
The problem is fixed when I pass a variable of the type `[]RomanNumeral` as the first argument.
```go
var allRomanNumerals = []RomanNumeral{
	{1000, "M"},
	{900, "CM"},
	{500, "D"},
	{400, "CD"},
	{100, "C"},
	{90, "XC"},
	{50, "L"},
	{40, "XL"},
	{10, "X"},
	{9, "IX"},
	{5, "V"},
	{4, "IV"},
	{1, "I"},
}

...
value := RomanNumerals.ValueOf(allRomanNumberals, potentialNumber)
```
When I do this the tests still fail.

**Comment by quii** [comment]
You need to be doing `allRomanNumerals.ValueOf(potentialNumber)`

Have a look here https://github.com/quii/learn-go-with-tests/blob/68e8173044142b7fe942f500d58349669458d58b/roman-numerals/v11/roman_numerals.go#L8

**Comment by quii** [comment]
To be fair to you, the markdown's snippets are slightly misleading/out-of-date so I've just fixed this
