### ISSUE TITLE
arrays and slices

### ISSUE THREAD

**Issue by Leamsi9** [quii/learn-go-with-tests#300]
Not sure whether you want to mention this as a strategy, but in the arrays and slices section you have:

> It's important to note that reflect.DeepEqual is not "type safe", the code will compile even if you did something a bit silly. To see this in action, temporarily change the test to:
> 
> func TestSumAll(t *testing.T) {
> 
>     got := SumAll([]int{1,2}, []int{0,9})
>     want := "bob"
> 
>     if !reflect.DeepEqual(got, want) {
>         t.Errorf("got %v want %v", got, want)
>     }
> }
> What we have done here is try to compare a slice with a string. Which makes no sense, but the test compiles! So while using reflect.DeepEqual is a convenient way of comparing slices (and other things) you must be careful when using it.
> 
That is really good to know, but it might be worth adding that if instead of using %v you had used the stricter %d in tErrorf, then the test would not compile, as it was expecting integers but got a string. So type checking your fmt output may be a good practice to recommend when testing numerical slices and arrays, particularly when using reflect.DeepEqual.

Totally new to Go and working through your brilliant curriculum. Let me know if I missed something obvious or using %d has a gotcha I don't know about.

**Comment by quii** [comment]
Incorrect formatting things (`%s, %d` etc) will not cause compilation problems, they'll just render weirdly.
