### ISSUE TITLE
Formatting issue on sync.md

### ISSUE THREAD

**Issue by lucas-deangelis** [quii/learn-go-with-tests#302]
In the Sync chapter, the new assertion function is the following:
```go
t.Run("it runs safely concurrently", func(t *testing.T) {
	wantedCount := 1000
	counter := Counter{}

	var wg sync.WaitGroup
	wg.Add(wantedCount)

	for i:=0; i<wantedCount; i++ {
		go func(w *sync.WaitGroup) {
			counter.Inc()
			w.Done()
		}(&wg)
	}
	wg.Wait()

	assertCounter(t, counter, wantedCount)
})
```
There is a small formatting issue on the for loop: there is no space between operators and operands. It's also a small coherence issue since the for loop is properly formatted in the code:
```go
t.Run("it runs safely concurrently", func(t *testing.T) {
	wantedCount := 1000
	counter := NewCounter()

	var wg sync.WaitGroup
	wg.Add(wantedCount)

	for i := 0; i < wantedCount; i++ {
		go func(w *sync.WaitGroup) {
			counter.Inc()
			w.Done()
		}(&wg)
	}
	wg.Wait()

	assertCounter(t, counter, wantedCount)
})
```
It may be due to not being able to run go fmt on the markdown. I can fix the issue, but since I'm really new to this I didn't want to open a pull request without properly explaining things first.

**Comment by quii** [comment]
Nice spot, feel free to raise a PR
