### ISSUE TITLE
Style nits

### ISSUE THREAD

**Issue by peterbourgon** [quii/learn-go-with-tests#309]
Nice repo, great attention to detail. Mostly :)

1. Go file names should be with_underscores.go, e.g. file_system_store.go not FileSystemStore.go
2. Block comments should be full sentences i.e. include trailing punctuation

**Comment by quii** [comment]
Thanks, I'm in general not very detail-oriented and need people to point out my laziness. Will take a look

**Comment by quii** [comment]
@peterbourgon Where is this documented? My searches seem to come up with some mixed signals https://github.com/golang/go/issues/36060

**Comment by peterbourgon** [comment]
[My response in that thread](https://github.com/golang/go/issues/36060#issuecomment-580269614).

**Comment by quii** [comment]
No shame here

```go
package main

import (
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	path := "."

	err := filepath.Walk(path, func(path string, f os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if strings.Contains(f.Name(), ".go") {
			file, err := ioutil.ReadFile(path)
			if err != nil {
				return err
			}

			lines := strings.Split(string(file), "\n")

			for i, line := range lines {
				if strings.HasPrefix(line, `//`) {
					lines[i] = lines[i] + "."
				}
			}
			output := strings.Join(lines, "\n")
			err = ioutil.WriteFile(path, []byte(output), 0644)
			if err != nil {
				return err
			}
		}
		return nil
	})

	if err != nil {
		log.Fatalf("problem opening %q, %v", path, err)
	}
}
```

**Comment by peterbourgon** [comment]
Haha brilliant :shipit:
