### ISSUE TITLE
[context] content of the book and repo differs

### ISSUE THREAD

**Issue by santosh** [quii/learn-go-with-tests#320]
I have difficulty following the chapter **context**. Is it just me?

In the `TestServer` function, the `data` variable is undefined. 

To match the source code to the book, I opened this repo just to find out that there is not even `SpyStore` defined.

**Comment by quii** [comment]
Yeah I sometimes struggle to keep it in sync, apologies! Will try and find some time to look into this chapter at some point

**Comment by canro91** [comment]
The book doesn't include instructions to add a delay greater than the cancellation timeout inside the `Fetch` function. I'm willing to open a PR to update the chapter
