### ISSUE TITLE
Question about Go reference types in the map charactper

### ISSUE THREAD

**Issue by chenxinlong** [quii/learn-go-with-tests#326]
Hi, I'm so confused about the "Reference type" in Go. I've seen a lot of articles mentioned golang reference types naturally, but also there's a lot of articles hold the view of "Go  has no reference type" such as : 

1. golang official commit message: https://github.com/golang/go/commit/b34f0551387fcf043d65cd7d96a0214956578f94  
2. go101 : https://www.tapirgames.com/blog/golang-has-no-reference-values

I saw the [Reference type](https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/maps#reference-types) on learn-go-with-test, so is that a mistake or Go indeed has reference type?

**Comment by quii** [comment]
@chenxinlong This is a really good point, the content was indeed wrong. I've correct it, thanks for raising this - sorry it took so long to fix!
