### ISSUE TITLE
Introducing `new` keyword on sync.md

### ISSUE THREAD

**Issue by dotm** [quii/learn-go-with-tests#330]
https://github.com/quii/learn-go-with-tests/blob/master/sync.md

In the sync.md, there's this snippet:
```
func NewCounter() *Counter {
	return &Counter{}
}
```

This might be a good opportunity to introduce the `new` keyword:
```
func NewCounter() *Counter {
	return new(Counter)
}
```

Though they are the same, this might give knowledge to some learners about the existence and functionality of the `new` keyword.

**Comment by quii** [comment]
I almost never use `new` though! I think in practice whilst `new(Counter)` feels convenient the moment you start adding fields to a type you have to undo and go back to `&Counter{initialValue: 10}` for instance.
