### ISSUE TITLE
Unnecessary for loop in `Reflection` chapter 

### ISSUE THREAD

**Issue by Yumasi** [quii/learn-go-with-tests#337]
In the `Reflection` chapter, in the part where we add channels support in the `walk` function, there is this for loop in the given solution:

```go
    for i:=0; i< numberOfValues; i++ {
        walk(getField(i).Interface(), fn)
    }
```

All tests pass without this loop (which I think was removed in previous refactors in the same chapter)

**Comment by quii** [comment]
oh nice spot! There was a recent PR around channels which maybe I didn't study as hard as I should've. 

Would be a bit help if you could drop a small PR @Yumasi , you'll get some internet points too!

**Comment by Yumasi** [comment]
You’re welcome ! I’ll do a PR for it soon. 🙂
