### ISSUE TITLE
pkg.go.dev has replaced godoc.org 

### ISSUE THREAD

**Issue by goujonbe** [quii/learn-go-with-tests#346]
Hi there,

Thank you for your work @quii .

In the [chapter about integers](https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/integers), you mention at the end that you can see the documentation of your package on [godoc.org](https://godoc.org/).

I think [this website has now been replaced by pkg.go.dev](https://blog.golang.org/pkg.go.dev-2020) since 2019. It might be confusing for newcomers.

I don't mind creating a small PR to address this issue. Would you be interested in such contribution?

**Comment by quii** [comment]
Yeah go for it!
