### ISSUE TITLE
Automate using gofmtmd

### ISSUE THREAD

**Issue by quii** [quii/learn-go-with-tests#353]
@benoittgt very kindly submitted a PR to fix some spacing issues in the markdown using [gofmtmd](https://github.com/po3rin/gofmtmd). 

It should be possible to automate this as part of the build script

**Comment by varmakarthik12** [comment]
I can own this. This is related to something I'm working on currently https://github.com/varmakarthik12/git-hooks.

**Comment by uppalabharath** [comment]
@varmakarthik12 I see there is no update in the last six months on this issue. So I thought of giving it a try. 
I see that you are trying to implement the git-hooks based integration to run various scripts during pre-commit. I fixed this particluar issue by directly downloading the gofmtmd lib as part of build,sh run and ran the tool and committed the files. 

@quii , @benoittgt Please review the PR https://github.com/quii/learn-go-with-tests/pull/498 and let me know if I missed anything or any other changes are needed. Thanks

**Comment by uppalabharath** [comment]
@quii Please let me know if there is anything pending regarding this issue. 
Thanks.
