### ISSUE TITLE
Lack of file names make the later chapters a little more challenging to follow

### ISSUE THREAD

**Issue by wulymammoth** [quii/learn-go-with-tests#357]
I was reviewing the chapter on context, but it required jumping to the repository featuring three child directories each mapped to different versions. The first one was missing `testdouble.go`, so this required sifting through the other two versions and needing to reconcile which worked best with the chapter.

EDIT: looks like v1 maps to the first iteration 

Love your work. I don't mind making a PR for this at a later time to make this easier for others and my future self going forward, but just thought I'd leave a note

**Comment by quii** [comment]
It has been one of the more challenging aspects of writing this book if I'm honest, trying to keep code samples in line with the markdown files and trying to get the pacing "right"

It would be great if you had time to raise a PR

**Comment by ReggieSean** [comment]
Also, If you could highlight  deleting a file, it could save newbies like me from some confusion:)
