### ISSUE TITLE
I want to translate the project into Japanese.

### ISSUE THREAD

**Issue by andmorefine** [quii/learn-go-with-tests#359]
Hello, I would like also to spread your lovely project in Japan.

The Japanese translation is still in progress, but if you like, could you add it to `README.md`?

`https://andmorefine.gitbook.io/learn-go-with-tests/`

If you find something strange, please point it out.
Thank you.

**Comment by quii** [comment]
@andmorefine That's great! I'll add a link.

I know very little Japanese so I won't be able to help too much! The other translations have been successful by reaching out to their respective local communities to get help with review, I'd encourage you to do the same. Good luck!

**Comment by quii** [comment]
Added a link, keep in touch @andmorefine !

**Comment by andmorefine** [comment]
@quii Thank you very much!

Your site is well used in Japan.
https://quii.gitbook.io/learn-go-with-tests/

Good luck to you!
