### ISSUE TITLE
Possible suggestions for improving the test code

### ISSUE THREAD

**Issue by damianoneill** [quii/learn-go-with-tests#36]
Chris I came across this [article](https://medium.com/@povilasve/go-advanced-tips-tricks-a872503ac859) is there value incorporating anything from this?

Damian.

**Comment by quii** [comment]
Yeah I've come across this before. I dont think anything we've done so far contradicts the advice, it's just we need to come up with real-world scenarios where we can fit them in. (e.g need an example with golden data). 

I feel it's important to show the various techniques against real-world scenarios.

If you look at my proposed table of contents so far there's two broad sections. Fundamentals and then Standard Lib essentials. We're nearly there with the fundamentals (i think), but the standard lib essentials is where we can maybe fit this stuff in.
