### ISSUE TITLE
Arrays and Slices Chapter - Refactor Section - contradicts benchmark tests

### ISSUE THREAD

**Issue by satyapadala** [quii/learn-go-with-tests#370]
https://github.com/quii/learn-go-with-tests/blob/24b7b9a3fa95f66690a19bdb4206bbd4ceb958b5/arrays/v5/sum.go#L13

At https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/arrays-and-slices#refactor-2, it has been recommended to refactor the code to use append function.

However, as per the benchmark tests that I did (thanks for teaching me how to do that), I find using append function causes more time to run the program:

arrays.go:

```
func SumAll(numbersToSum ...[]int) (sums []int) {
	var result []int
	for _, arr := range numbersToSum{
		result = append(result, Sum(arr))
	}
	return result
}

func SumAllNotRefactored(numbersToSum ...[]int) (sums []int) {
	result := make([]int, len(numbersToSum))
	for i, arr := range numbersToSum{
		result[i] = Sum(arr)
	}
	return result
}
```

arrays_test.go:

```
func BenchmarkSumAll(b *testing.B) {
	for i:=0;i< b.N;i++ {
		SumAll([]int{1,2,3,1,2},[]int{1,1,2,2},[]int{3,4,3})
	}
}

func BenchmarkSumAllNotRefactored(b *testing.B) {
	for i:=0;i< b.N;i++ {
		SumAllNotRefactored([]int{1,2,3,1,2},[]int{1,1,2,2},[]int{3,4,3})
	}
}
```

Output:

```
goos: darwin
goarch: amd64
pkg: github.com/satyapadala/hello/arrays
BenchmarkSumAll
BenchmarkSumAll-12                 	11451423	       105 ns/op
BenchmarkSumAllNotRefactored
BenchmarkSumAllNotRefactored-12    	29080730	        37.5 ns/op
PASS

Process finished with exit code 0
```

**Comment by Akhpatel** [comment]
This is expected as append creates a new underlying array by first copying the original array and then adding the appended data. It would be faster to not use append if we know before hand the size of the new slice that will be required. But doing so would rob us of an opportunity to introduce the append function. 
Refer to this blog post for details about how copy and append functions work: https://blog.golang.org/slices-intro
