### ISSUE TITLE
Interest in taking on "go-koans"

### ISSUE THREAD

**Issue by Dannyzen** [quii/learn-go-with-tests#4]
This project seems (?) to be similar to [cdarwin/go-koans](https://github.com/cdarwin/go-koans). Any thoughts on taking on that project or using it to inspire this one?

**Comment by quii** [comment]
Hi

There are definitely parallels and I am not 100% clear what direction this project will take.

Here are my broad objectives for users

- Learn and understand TDD
- Get a broad understanding of Go's syntax (channels, if, switch, select etc) (by writing tests)
- Get an increased understanding of Go's stdlib (by writing tests)
- How to structure applications so they are testable (by writing tests)

Notice the emphasis on _writing tests_. I think Koans are nice, but the tests are written for you already. 

I want to help users develop the skills necessary to write good tests. Koans are like a tour of the language, I want something a bit higher level than that.

**Comment by Dannyzen** [comment]
Well said and imho a great goal!
