### ISSUE TITLE
Travis build fails

### ISSUE THREAD

**Issue by khmarbaise** [quii/learn-go-with-tests#404]
The travis build fails because travis has stopped to support OSS... ?

**Comment by quii** [comment]
It seems to be ok? https://travis-ci.org/github/quii/learn-go-with-tests

Having a quick look at the build history it seemed to fail pulling the pandoc docker image but that seems to have resolved itself

Did you have anymore detail @khmarbaise  ?

**Comment by khmarbaise** [comment]
Looks fine. But quote from the side: `Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information.`  I have migrated all my oss to Github actions or drone.io.
