### ISSUE TITLE
.profile is not executed if .bash_profile exists. User may break their profile

### ISSUE THREAD

**Issue by schellingerhout** [quii/learn-go-with-tests#413]
Per the header of .profile. If a .bash_profile is present the .profile is not read

```
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
```
Instructions to update .bash_profile may lead a user to create a new .bash_profile while a .profile is already present. 

(Platform: Ubuntu 20.04.2 LTS)

**Comment by westminsterabi** [comment]
Can I claim this?

**Comment by quii** [comment]
I'm going to fix this by removing any kind of Go setup or editor setup. It's not the purpose of this book to teach this and it's a drag to keep updating it when there are existing resources already for people to find out how to do this.
