### ISSUE TITLE
Code font makes it very hard to distinguish ( and {

### ISSUE THREAD

**Issue by lquenti** [quii/learn-go-with-tests#415]
The font used for code snippets makes it really hard to distinguish, especially when learning a language where one can't predict whether a constructor needs curly or normal braces.

**Comment by lquenti** [comment]
Oh, the one used by Gitbook btw

**Comment by quii** [comment]
I'm not sure there's much I can do about this, so I am going to close I'm afraid. May I suggest you view the files on github instead? Or perhaps try epub (check the releases page) where AFAIK you can configure your epub reader to render things how you'd like? https://github.com/quii/learn-go-with-tests/releases
