### ISSUE TITLE
Section:Integers - Suggestion

### ISSUE THREAD

**Issue by kumarsourav** [quii/learn-go-with-tests#42]
While running go test with the ExampleAdd() function, I observed that if we remove the comment(Output: 6), the test will not execute this function. I checked the go documents and found out 
here - [https://golang.org/pkg/testing/#hdr-Examples](url)

> Example functions without output comments are compiled but not executed

May be we can add this as a note in Integers Section ?

**Comment by quii** [comment]
Hi @kumarsourav , great suggestion! 

Do you feel comfortable making the edit yourself via a pull request? You can then get credit for it on here as a contributor 🥇

**Comment by kumarsourav** [comment]
Thanks Chris. I have created a pull request. Please review.

**Comment by quii** [comment]
Thanks!
