### ISSUE TITLE
Add a note about `go mod init`?

### ISSUE THREAD

**Issue by telemachus** [quii/learn-go-with-tests#428]
On `go 1.16`, commands like `go test` fail with the dreaded `go: cannot find main module; see 'go help modules'` error.

Maybe add a note at the front of the book about `go mod init` for people new to go and to the book? (I'd happily make a PR, but I'm new enough to go that I'm not sure I'd get it right.)

(PS I'm loving the book: thanks for it. Sorry to repay you with two issues in one day.)

**Comment by quii** [comment]
@telemachus I appreciate the issues! No worries

You're quite right! I'm my zeal to remove the $GOPATH stuff, i forgot to add the `go mod init` instruction. I'd love for you to get some internet points but I'm keen to address this quickly. Do you think you could get a PR done soonish and I'll get it merged?

**Comment by telemachus** [comment]
I wrote a quick paragraph and just submitted it. I'm not worried about the internet points, lol, but I do want to help.

That said, my own understanding of modules is still pretty rudimentary. I obviously wont' be offended if you heavily edit or even completely scrap my draft. Do whatever makes the most sense!
