### ISSUE TITLE
I want to translate the project into Korean

### ISSUE THREAD

**Issue by MiryangJung** [quii/learn-go-with-tests#432]
Hello. I want to translate this amazing project into Korean.

I already found an issue that translate into Korean, but I saw it stopped since 1 years ago.
Therefore, I posted [issue](https://github.com/Gunforge/learn-go-with-tests-ko/issues/55) where the Korean translation was originally proceed.

I'm already doing the translation and it's expected to be finished within a month.

[github.com/MiryangJung/learn-go-with-tests-ko](https://github.com/MiryangJung/learn-go-with-tests-ko)

I will request for help from the Korea Developers Community.

If the original translator allows the translation, Can I proceed?

Thank you.

**Comment by MiryangJung** [comment]
Hello! translate work on progress in [here](https://github.com/MiryangJung/learn-go-with-tests-ko)
Gitbook Link : https://miryang.gitbook.io/learn-go-with-tests/

**Comment by quii** [comment]
I'll add a link, just to check @MiryangJung would "한국어" be correct for the link?

**Comment by MiryangJung** [comment]
YES! 

[한국어](https://miryang.gitbook.io/learn-go-with-tests/)

THANK YOU.

**Comment by quii** [comment]
No, thank you for making the effort to get it translated, I wish you luck! 

https://github.com/quii/learn-go-with-tests/commit/6a976048b7eda9b7fe582749d93045aed9e98f3e

**Comment by quii** [comment]
Sent a tweet out to see if anyone else can help you out too

https://twitter.com/quii/status/1370014740165111810

**Comment by MiryangJung** [comment]
Thank you for your help. :)
I will back when the translation is completed.

**Comment by quii** [comment]
Closing this here as it looks like there's a lot of good progress going here but I can't really contribute. The link is in the readme for people to find the translation
