### ISSUE TITLE
Remove or Rename $GOPATH instructions in Install

### ISSUE THREAD

**Issue by carmo-evan** [quii/learn-go-with-tests#434]
[According to the Go developer survey](https://blog.golang.org/survey2020-results#TOC_8.), 96% of Go developers currently use Go modules. It is the de facto standard and the $GOPATH approach should be phased out. The new paragraph added does a great job in communicating that.

However,  right now the $GOPATH instructions come before the Go modules instructions, and that can cause a great deal of confusion. I frequent some chat rooms where new Go developers deal with issues trying to use go modules alongside with $GOPATH every day, and it can get pretty troublesome to untangle. I think as a book directed to beginners, this project can do much good if it directs people to use go modules primarily.

Having that in mind, I believe that can be accomplished by removing the $GOPATH section, or placing the $GOPATH section somewhere after the Go modules section, with a very visible disclaimer that working that way is deprecated.

**Comment by quii** [comment]
Agreed!
