### ISSUE TITLE
I would like to translate the project to Spanish

### ISSUE THREAD

**Issue by josevill** [quii/learn-go-with-tests#438]
I've been looking for guides on Testing with GO because I've kind of neglected it in the past, the best way to learn and reassure some knowledge is to teach others.

Although the content is already written, translating it and giving it some context in Spanish is still a challenge.

I will do it if given the permission by the owner.

I can devote a couple hours a day, so I hopefully should be done pretty soon!

**Comment by quii** [comment]
More than happy for you to do this! Thanks for volunteering to take on this work. 

All I ask is that, like [the other translations](https://larien.gitbook.io/aprenda-go-com-testes/) it links back to the English version and maintains that the content's attribution is to the original project. 

Let me know how it goes and I'll add it to the [list of translations](https://github.com/quii/learn-go-with-tests#translations)

**Comment by tobyjwebb** [comment]
@josevill Hi! How is the translation going, do you need help?

**Comment by quii** [comment]
There seems to be a fork but it doesn't have any new commits that I can see

**Comment by tobyjwebb** [comment]
I didn't check if he'd forked the repo, but he might have some unpushed work, or something of the sort. I would like to help, but duplicating efforts is kinda boring :) - which is why I asked... Oh, I love the book, by the way <3 :)

**Comment by tobyjwebb** [comment]
:( - No response. Ok - gonna fork. Wish me luck! :)

**Comment by tobyjwebb** [comment]
This is gonna be more work than I thought :sweat_smile: 

For those that are interested in helping (or if I disappear), the fork is [here](https://github.com/tobyjwebb/learn-go-with-tests/tree/spanish-translation), in the `spanish-translation` branch.

**Comment by quii** [comment]
Let me know when you've got a few chapters done and I'll add it to the translations list. I can spam twitter a bit for help if you like? Do you have an account I can tag?

**Comment by tobyjwebb** [comment]
Hi Chris!

As you can see from [here](https://github.com/tobyjwebb/learn-go-with-tests/pull/1/files#diff-0aea121101cd1105f76f8d6f0a729aaece7cda2f92c925dac6b56982ce947a62R50), there's a small way to go yet.

I haven't got a Twitter account I use... (Or many social networks for that matter :D )

I'll keep cracking on at it every now and again, and see if anyone notices this issue who can be in a position to help.

**Comment by quii** [comment]
Doesn't seem to be much progress on this, closing for now

**Comment by tobyjwebb** [comment]
Yes, sorry, my attention has been focused elsewhere lately... I'll try to
get back to it at some point...

Happy holidays!

**Comment by NachoBrito** [comment]
Hi! I'm working on a new translation here: https://github.com/NachoBrito/aprende-go-mediante-tests  

I'm aware it's a very big effort so any help will be welcome, I've set up a project with  a task for each chapter. Please let me know if you would be interested in getting access to the repo so we can collaborate 🙂

**Comment by tobyjwebb** [comment]
Hi Nacho.

Unfortunately, I haven't got much time lately :(

Regarding assigning time & effort to translate this text - I've thought on this subject, and come to the conclusion that it might be a better idea for potential readers to go to the English version instead. Most documentation regarding programming found on the internet is already available in English, so in the long term, so if a person is interested in learning programming, learning English is nearly a prerequisite. (Except maybe entry-level tutorials.)

What I do instead is point people to this repo when the subject arises. :shrug: 

Saludos
