### ISSUE TITLE
Incorrect error handling of http.ListenAndServe

### ISSUE THREAD

**Issue by fossegrim** [quii/learn-go-with-tests#439]
In the following snippet copied from https://quii.gitbook.io/learn-go-with-tests/build-an-application/http-server you handle the `http.ListenAndServe` error incorrectly.

```go
package main

import (
    "log"
    "net/http"
)

func main() {
    handler := http.HandlerFunc(PlayerServer)
    if err := http.ListenAndServe(":5000", handler); err != nil {
        log.Fatalf("could not listen on port 5000 %v", err)
    }
}
```

A non-nil return value is always returned regardless of whether it could or "could not listen on port 5000".

It should be replaced by something like the following:

```go
package main

import (
    "log"
    "net/http"
)

func main() {
    handler := http.HandlerFunc(PlayerServer)
   log.Fatal(http.ListenAndServe(":5050", nil))
}
```

https://pkg.go.dev/net/http#ListenAndServe

**Comment by quii** [comment]
TIL, will fix. Thanks for raising

**Comment by fossegrim** [comment]
Thanks
