### ISSUE TITLE
Add chapter about go template feature

### ISSUE THREAD

**Issue by sailing0505** [quii/learn-go-with-tests#441]
go template feature is powerful but complex. I hope someone could add some tests for learning. Thank you.

**Comment by quii** [comment]
OK so I thought I'd start writing some thoughts on this

## What I'd like people to learn

- The basics of loading templates, sending data to them and getting them rendered
- Caching the templates
- A little detail on some of the features, like if, for, e.t.c. Don't need to go overboard, there's plenty of docs out there for people who want to find out more
- How to design your code so they're simple to test

## How to test

Templates are tricky to test. An overriding principal is you should try and keep templates simple. If you're thinking deeply about separation of concerns you should recognise that templates should be primarily concerned with taking static set of data and transforming it into a string.

A mistake people make is encoding important business logic in templates, and not thinking about separation of concerns well-enough. The logic itself has nothing to do with presentation, but now you've put it into the template you've now made it more difficult to find, understand and test. 

### Some approaches

To be really confident, and to have a good test suite, you'll probably need at least 2 of the following:

1. [Approval tests](https://approvaltests.com) are a neat testing approach for testing stuff where you don't really _care_ about the specific details, but if the end result changes, you would want to know about it, and approve the change if necessary. The idea is, if you changed the markup slightly, you'd see the test fail but then "approve" the change to fix the test. However if you introduced a bug, the test would still let you know
2. Discuss the idea of "View Models", which are just a bag of data optimised for the rendering engine. The idea being to minimise the amount of logic the view (e.g the template) has to do, and allow you to test it separately. If you're confident that the code that calls the templates is generating the right view models, you're probably fine. Another spin on separation of concerns. 
3. Browser tests. Give ultimate confidence that the template you're rendering is useful to a real-ish user. Compared to unit tests though, they're slow to run, hard to write, and often don't give the most helpful of errors when they fail.

## Exercise to centre around

In the [Reading Files](https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/reading-files) chapter, we take some markdown files for a blog engine and convert them into some objects of type `Post`

```go
type Post struct {
    Title, Description, Body string
    Tags []string
}
```

This chapter could carry on this theme and render a blog as HTML

```
// given a slice of `Post`
// when I send it to my `RenderingEngine` ??
// then I produce a HTML index page
// and individual HTML pages for each post
```

**Comment by quii** [comment]
Going to take notes as I explore and write this thing! 

## Thoughts

Important to think about requirements before diving in too fast. What do we want to render?
- Individual posts, so if I hit `myblog.com/posts/somepost.html` I get something
- An index page

In my view, actually viewing content is higher priority than an index page. I could always launch this "product" and share direct links. 

Start with a simple test, thinking **API first**

```go
package blogrenderer_test

import (
	"bytes"
	"github.com/quii/learn-go-with-tests/blogrenderer"
	"testing"
)

func TestRender(t *testing.T) {
	var (
		aPost = blogrenderer.Post{
			Title:       "hello world",
			Body:        "This is a post",
			Description: "This is a description",
			Tags:        []string{"go", "tdd"},
		}
	)

	t.Run("it converts a single post into HTML", func(t *testing.T) {
		want := `<h1>hello world</h1>`
		buf := bytes.Buffer{}
		err := blogrenderer.Render(&buf, aPost)

		if err != nil {
			t.Fatal(err)
		}

		got := buf.String()
		if got != want {
			t.Errorf("got '%s' want '%s'", got, want)
		}
	})
}
```

At this stage I'm not overly concerned with the specific markup, and an easy first step would be just to check we can render the post's title as an `<h1>`. This _feels_ like the smallest first step that can move us forward a bit.

**Comment by quii** [comment]
The code to make this pass

```go
func Render(w io.Writer, p Post) error {
	_, err := fmt.Fprintf(w, "<h1>%s</h1>", p.Title)
	return err
}
```

Notice we're not worrying about using templates right now. You can make HTML just with "normal" string templating just fine, and by skipping the template part we can validate a small bit of useful behaviour.

**Comment by quii** [comment]
## Next iteration

Now we have a very basic version working, we can now iterate on the test to expand on the functionality. In this case, adding more information from the `Post`.

```go
	t.Run("it converts a single post into HTML", func(t *testing.T) {
		want := `<h1>hello world</h1>
<p>This is a description</p>
Tags: <ul><li>go</li><li></li></ul>`
		buf := bytes.Buffer{}
		err := blogrenderer.Render(&buf, aPost)

		if err != nil {
			t.Fatal(err)
		}

		got := buf.String()
		if got != want {
			t.Errorf("got '%s' want '%s'", got, want)
		}
	})
```

Notice that writing this, _feels_ a bit rubbish. Seeing all that markup in the test feels naff, and we haven't even put the body in, or the actual HTML we'd want with all of the `<head>` content and whatever page furniture we need. 

Nonetheless, let's put up with the pain _for now_.

**Comment by quii** [comment]
## Introducing templates

Go has two (I think, need to check) templating packages text/template and html/template. The HTML one is a more specialised version of the text one. What they both do is allow you to is combine a template and some data to produce a string. The templating language is very similar to handlebars and allows you to dynamically generate content in a very clean fashion with a nice separation of concerns. 

Here is a template for our blog: `<h1>{{.Title}}</h1><p>{{.Description}}</p>Tags: <ul>{{range .Tags}}<li>{{.}}</li>{{end}}</ul>`

**TODO** Explain the syntax, link to docs, yada yada

Where do we define this string? Well, we have a few options, but to keep the steps small, let's just start with a plain old string

```go
package blogrenderer

import (
	"html/template"
	"io"
)

const (
	postTemplate = `<h1>{{.Title}}</h1><p>{{.Description}}</p>Tags: <ul>{{range .Tags}}<li>{{.}}</li>{{end}}</ul>`
)

func Render(w io.Writer, p Post) error {
	templ, err := template.New("blog").Parse(postTemplate)
	if err != nil {
		return err
	}

	err = templ.Execute(w, p)
	if err != nil {
		return err
	}

	return err
}
```

This should be a pure refactor. We shouldn't need to change our tests and they should continue to pass. Importantly, our code is far easier to read and has far less annoying error handling to contend with. Frequently people complain about the verbosity of error handling in Go, but often you might find you can find better ways to write your code so it's less error-prone in the first place, like here.

**Comment by quii** [comment]
## Next refactor: Move in to file

Using the `html/template` has definitely been an improvement but having it as a string constant in our code still isn't great

- Still quite difficult to read
- Not IDE/editor friendly. No syntax highlighting, ability to reformat, refactor, e.t.c.
- It looks like HTML, but you can't really work with it like you could a "normal" HTML file

What we'd really like to do is have our templates live in separate files so we can better organise them, and work with them as if they're HTML files

Create a folder called "templates" and inside it make a file called `blog.template.html`, paste our template into the file

Now change our code to embed the file systems using the embedding functionality included in go 1.16

```go
package blogrenderer

import (
	"embed"
	_ "embed"
	"html/template"
	"io"
)

var (
	//go:embed "templates/*"
	postTemplates embed.FS
)

func Render(w io.Writer, p Post) error {
	templ, err := template.ParseFS(postTemplates, "templates/*.template.html")
	if err != nil {
		return err
	}

	if err := templ.Execute(w, p); err != nil {
		return err
	}

	return nil
}
```

TODO: explain embed! Relate to the fs.FS stuff we saw in the reading files chapter.

By embedding a "file system" into our code, we can load multiple templates and combine them freely. This will become useful when we want to share rendering logic across different templates, such as a header for the top of the HTML page and a footer.

**Comment by quii** [comment]
## Next: Make the template "nice"

We don't really want our template to be defined as a one line string. We want to be able to space it out to make it easier to read and work with, something like this

```go
<h1>{{.Title}}</h1>

<p>{{.Description}}</p>

Tags: <ul>{{range .Tags}}
    <li>{{.}}</li>
{{end}}</ul>
```

But if we do this, our test fails. This is because our test is expecting a very specific string to be returned. But really, we don't actually care about whitespace. Maintaining this test will become a nightmare if we have to keep painstakingly updating the assertion string every time we make minor changes to the markup.

**Comment by quii** [comment]
## Introducing Approval Tests

[Go Approval Tests](https://github.com/approvals/go-approval-tests)

> ApprovalTests allows for easy testing of larger objects, strings and anything else that can be saved to a file (images, sounds, csv, etc...)

The idea is similar to "golden" files, or snapshot testing. Rather than awkwardly maintaining strings within a test file, the approval tool can compare the output for you against an "approved" file you created. You then simply copy over the new version if you approve it. Re-run the test and you're back to green.

Add a dependency to `"github.com/approvals/go-approval-tests"` to your project and edit the test to the following

```go
package blogrenderer_test

import (
	"bytes"
	approvals "github.com/approvals/go-approval-tests"
	"github.com/quii/learn-go-with-tests/blogrenderer"
	"testing"
)

func TestRender(t *testing.T) {
	var (
		aPost = blogrenderer.Post{
			Title:       "hello world",
			Body:        "This is a post",
			Description: "This is a description",
			Tags:        []string{"go", "tdd"},
		}
	)

	t.Run("it converts a single post into HTML", func(t *testing.T) {
		buf := bytes.Buffer{}
		err := blogrenderer.Render(&buf, aPost)

		if err != nil {
			t.Fatal(err)
		}

		got := buf.String()
		approvals.VerifyString(t, got)
	})
}
```

The first time you run it, it will fail because we haven't approved anything yet

```
=== RUN   TestRender
=== RUN   TestRender/it_converts_a_single_post_into_HTML
    renderer_test.go:29: Failed Approval: received does not match approved.
```

It will have created two files, that look like the following

- `renderer_test.TestRender.it_converts_a_single_post_into_HTML.received.txt`
- `renderer_test.TestRender.it_converts_a_single_post_into_HTML.approved.txt`

The received file has the new, unapproved version of the output. Copy that into the empty approved file and re-run the test. 

By copying the new version you have "approved" the change, and the test now passes. 

To see the workflow in action, edit the template to how we discussed to make it easier to read (but semantically, it's the same)

```go
<h1>{{.Title}}</h1>

<p>{{.Description}}</p>

Tags: <ul>{{range .Tags}}
    <li>{{.}}</li>
{{end}}</ul>
```

Re-run the test. A new "received" file will be generated because the output of our code differs to the approved version. Give them a look, and if you're happy with the changes, simply copy over the new version and re-run the test. Be sure to commit the approved files to source control.

The advantage of this approach is you can more easily use tools like diff tools to see the difference, and it keeps your test code cleaner.

**Comment by quii** [comment]
## Expanding upon the markup

Most websites have a little more HTML than we have right now. For starters, a `html` element, along with a `head`, perhaps some `nav` too. Usually there's an idea of a footer too. 

If our site is going to have different pages, we'd want to define these things in one place to keep our site looking consistent. Go templates support us defining sections which we can then import in to other templates.

Edit our existing template to import a top and bottom template

```go
{{template "top" .}}
<h1>{{.Title}}</h1>

<p>{{.Description}}</p>

Tags: <ul>{{range .Tags}}<li>{{.}}</li>{{end}}</ul>
{{template "bottom" .}}
```

Then create `top.gohtml` with the following

```go
{{define "top"}}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>My amazing blog!</title>
    <meta charset="UTF-8"/>
    <meta name="description" content="Wow, like and subscribe, it really helps the channel guys" lang="en"/>
</head>
<body>
<nav role="navigation">
    <div>
        <h1>Budding Gopher's blog</h1>
        <ul>
            <li><a href="/">home</a></li>
            <li><a href="about">about</a></li>
            <li><a href="archive">archive</a></li>
        </ul>
    </div>
</nav>
<main>
{{end}}
```

And `bottom.gohtml`

```go
{{define "bottom"}}
<footer>
    <ul>
        <li><a href="https://twitter.com/quii">Twitter</a></li>
        <li><a href="https://github.com/quii">GitHub</a></li>
    </ul>
</footer>
</main>
</body>
</html>
{{end}}
```

Re-run your test. A new "received" file should be made and the test will fail. Check it over and if you're happy, approve it by copying it over the old version. Re-run the test again and it should be passing

**Comment by quii** [comment]
## An excuse to mess around with Benchmarking

Before pressing on, we should consider what our code does

```go
func Render(w io.Writer, p Post) error {
	templ, err := template.ParseFS(postTemplates, "templates/*.gohtml")
	if err != nil {
		return err
	}

	if err := templ.Execute(w, p); err != nil {
		return err
	}

	return nil
}
```

- Parse the templates
- Use the template to render a post to an `io.Writer`

Whilst the performance impact of re-parsing the templates in most cases will be fairly negligible, the effort to _not_ do this is also pretty negligible and should tidy the code up a bit too. 

To see the impact of not doing this parsing over and over, we can use the benchmarking tool to see how fast our function is. 

```go
func BenchmarkRender(b *testing.B) {
	var (
		aPost = blogrenderer.Post{
			Title:       "hello world",
			Body:        "This is a post",
			Description: "This is a description",
			Tags:        []string{"go", "tdd"},
		}
	)

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		blogrenderer.Render(io.Discard, aPost)
	}
}
```

On my computer, here are the results

`BenchmarkRender-8   	   22124	     53812 ns/op`

To stop us having to re-parse the templates over and over, we'll create a type that'll hold the parsed template, and that'll have a method to do the rendering

```go
type PostRenderer struct {
	templ *template.Template
}

func NewPostRenderer() (*PostRenderer, error) {
	templ, err := template.ParseFS(postTemplates, "templates/*.gohtml")
	if err != nil {
		return nil, err
	}
	
	return &PostRenderer{templ: templ}, nil
}

func (r *PostRenderer) Render(w io.Writer, p Post) error {
	
	if err := r.templ.Execute(w, p); err != nil {
		return err
	}

	return nil
}
```

This does change the interface of our code, so we'll need to update our test

```go
func TestRender(t *testing.T) {
	var (
		aPost = blogrenderer.Post{
			Title:       "hello world",
			Body:        "This is a post",
			Description: "This is a description",
			Tags:        []string{"go", "tdd"},
		}
	)

	postRenderer, err := blogrenderer.NewPostRenderer()

	if err != nil {
		t.Fatal(err)
	}

	t.Run("it converts a single post into HTML", func(t *testing.T) {
		buf := bytes.Buffer{}

		if err := postRenderer.Render(&buf, aPost); err != nil {
			t.Fatal(err)
		}

		approvals.VerifyString(t, buf.String())
	})
}
```

And our benchmark

```go
func BenchmarkRender(b *testing.B) {
	var (
		aPost = blogrenderer.Post{
			Title:       "hello world",
			Body:        "This is a post",
			Description: "This is a description",
			Tags:        []string{"go", "tdd"},
		}
	)

	postRenderer, err := blogrenderer.NewPostRenderer()

	if err != nil {
		b.Fatal(err)
	}

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		postRenderer.Render(io.Discard, aPost)
	}
}
```

The test should continue to pass. How about our benchmark?

`BenchmarkRender-8   	  362124	      3131 ns/op`. The old NS per op were ` 53812 ns/op`, so this is a decent improvement! As we add other methods to render say an Index page though, it should simplify the code as we don't need to duplicate the template rendering.

**Comment by quii** [comment]
https://github.com/quii/learn-go-with-tests/releases/tag/12.5.0 Hope that covers what you'd expect @sailing0505
