### ISSUE TITLE
chapter about documentation: dependency injection chapter difficult to follow

### ISSUE THREAD

**Issue by philipphanemann** [quii/learn-go-with-tests#458]
Hello, 
since I was not able to find another option to ask, I do it here. 

Within the chapter [dependency injection](https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/dependency-injection#refactor), it is stated "an io.Writer which we know both os.Stdout and bytes.Buffer implement". I am new to the language and could perfectly follow up to this point. Unfortunately, there I am stuck. From my point of view it would be very helpful to say how you get to the statement "which we know". This probably gets me to the point, how to properly read the documentation. At least these two methods are not used before, which makes it a bit hard for me. 

Best regards

**Comment by quii** [comment]
Hi @philipphanemann 

I've added more notes into the chapter in (https://github.com/quii/learn-go-with-tests/commit/ac99b8a2a028c2fe0471b1a67651e0f8293ebadd) - hopefully that clear things up.
