### ISSUE TITLE
map chapter

### ISSUE THREAD

**Issue by quii** [quii/learn-go-with-tests#47]
We've got a few chapters in progress that uses `map`s but have not actually explained them! 

Could be a potentially interesting chapter as they can be used in a number of ways

- Key/Value store (obviously)
- Sets

Could cover that they are not safe for concurrent use

**Comment by Rmstak** [comment]
quii

**Comment by quii** [comment]
Great news! 

That sounds good. As im sure you're aware, I'd advise you to try and stick with the TDD process, starting with something simple and iterating over it to build something more complex. I think that works well. 

See contributing.md and template.md for more help. 

But most of all, thanks for taking this on and im sure it'll be great :) Don't hesitate to go to the gopher slack to get feedback on drafts.

**Comment by hackeryarn** [comment]
If anyone that's watching this issue would like to follow along with the progress. I am working on the chapter [here](https://github.com/hackeryarn/learn-go-with-tests/blob/maps-chapter/maps.md).

I would appreciate any early feedback :smiley:

**Comment by quii** [comment]
Looks good so far, looking forward to seeing more

**Comment by hackeryarn** [comment]
@quii where do you think is the best place for this chapter to go? I tried to keep this chapter at a level where it could go right after the `Arrays and slices` chapter. However, using `errors` was the best way to demonstrate the two value return of a Map.

Do you think I should convert what I have to use dictionary `struct` and put it after the `Pointers & errors` chapter? Or do you have another suggestion of a way to make it fit after the `Arrays and slices` chapter. (Feel free to take a look at my branch for my current use of `errors`.)

**Comment by quii** [comment]
> Do you think I should convert what I have to use dictionary struct 

What do you mean by this?

Either way, I like your usage of errors so feel free to change the chapter order so feel free to change it.

Keep up the good work 👍

**Comment by quii** [comment]
I like the latter personally :) 

i really want to push the idea that you can put methods on _anything_ in Go, coz it's really cool
