### ISSUE TITLE
Using Mutex in sync chapter outside the struct

### ISSUE THREAD

**Issue by dunefro** [quii/learn-go-with-tests#473]
I found using the mutex in struct quite unabstracted. As mutex is defined 

> A Mutex is used to provide a locking mechanism to ensure that only one Goroutine is running the critical section of code at any point in time to prevent race conditions from happening.

We can simply put the mutex struct out of the structure to inside the for loop 
sync_test.go
```
package v1

import (
	"sync"
	"testing"
)

func TestCounter(t *testing.T) {

	t.Run("incrementing the counter 3 times leaves it at 3", func(t *testing.T) {
		counter := Counter{}
		counter.Inc()
		counter.Inc()
		counter.Inc()

		assertCounter(t, counter, 3)
	})

	t.Run("it runs safely concurrently", func(t *testing.T) {
		wantedCount := 1000
		counter := Counter{}

		var wg sync.WaitGroup
		var mu sync.Mutex
		wg.Add(wantedCount)

		for i := 0; i < wantedCount; i++ {
			go func() {
				// Added lock here
				mu.Lock()
				// Critical section of code to avoid race condition
				counter.Inc()
				// Unlock here
				mu.Unlock()
				wg.Done()
			}()
		}
		wg.Wait()

		assertCounter(t, counter, wantedCount)
	})

}

func assertCounter(t testing.TB, got Counter, want int) {
	t.Helper()
	if got.Value() != want {
		t.Errorf("got %d, want %d", got.Value(), want)
	}
}
```

With the `sync.go` will be something like this
```
package v1

type Counter struct {
	count int
}

func (c *Counter) Inc() {
	c.count++
}

func (c *Counter) Value() int {
	return c.count
}
```

With this way it will become more easy to follow and understand the code as well usage of mutex.

**Comment by quii** [comment]
I guess we'll have to agree to disagree here. The point here is to make a concurrent-safe counter, something that encapsulates this concern away from the outside world.
