### ISSUE TITLE
Order of assertion

### ISSUE THREAD

**Issue by kshuta** [quii/learn-go-with-tests#474]
Within the chapter ### Pointers & errors, the final code regarding the Withdraw test is as the following:
```
assertBalance(t, wallet, Bitcoin(10))
assertNoError(t, err)
```

Since the outcome of the function maybe completely meaningless if there is an error, should we not check for errors before asserting the balance :
```
assertNoError(t, err)
assertBalance(t, wallet, Bitcoin(10))
```

**Comment by quii** [comment]
@kshuta Good spot
