### ISSUE TITLE
How does it know how to access these variables?

### ISSUE THREAD

**Issue by okbrown** [quii/learn-go-with-tests#481]
https://github.com/quii/learn-go-with-tests/blob/5eddfad716b6858abfffb2827a3da2f7424de5d9/hello-world/v7/hello_test.go#L26-L36

- How does it know how to access these variables? 
- I am assuming this is on some type of global scope? 
- What are the rules about global scope in Go?

**Comment by quii** [comment]
What variables are you referring to?
