### ISSUE TITLE
Minor case missing in arrays-and-slices section

### ISSUE THREAD

**Issue by avoidik** [quii/learn-go-with-tests#482]
Hi,

In the arrays-and-slices section in the test for `SumAllTails` function we were testing cases when arrays can be empty or bigger than 1, a case when input array has `[]int{1}` is missing. What do you think, is it worth to add it?

```golang
    t.Run("safely sum empty slices", func(t *testing.T) {
        got := SumAllTails([]int{}, []int{1}, []int{3, 4, 5})
        want := []int{0, 0, 9}
        checkSums(t, got, want)
    })
```

**Comment by quii** [comment]
I don't think so. A lot of the time in this book you'll find places where I haven't covered everything, purely for brevity's sake. Thanks for raising nonetheless <3
