### ISSUE TITLE
Rename CountdownOperationsSpy to SpyCountdownOperations

### ISSUE THREAD

**Issue by markdl-dev** [quii/learn-go-with-tests#487]
Hello, 

In the Mocking chapter there are Spy types introduced
- SpySleeper
- SpyTime
- CountdownOperationsSpy

Will renaming CountdownOperationsSpy to SpyCountdownOperations make it more consistent?

**Comment by quii** [comment]
Yup, feel free to raise a PR to fix :)

**Comment by markdl-dev** [comment]
alright! and here is the PR #488
