### ISSUE TITLE
[time] function types, StdOutAlerter

### ISSUE THREAD

**Issue by hslabbert** [quii/learn-go-with-tests#496]
I think it might be helpful in https://github.com/quii/learn-go-with-tests/blob/main/time.md, when discussing user fined defined function types, to indicate that the updated `NewGame()` or `NewTexasHoldem()` call in https://github.com/quii/learn-go-with-tests/blob/92d7d2e33af97469ac6978bd5c94eb5055e23bb5/time/v2/cmd/cli/main.go#L21 is not actually providing `poker.StdOutAlerter` as an _argument_ to `poker.BlindAlerterFunc`, but is _casting_ it as a `poker.BlindAlerterFunc` type in order to also receive the `ScheduleAlertAt()` function definition and hence satisfy the `BlindAlerter` interface.

Honestly that line really fried my brain for a bit. I could grok that `StdOutAlerter()` satisfied the `BlindAlerterFunc()` signature, but got stuck on reading that as if `poker.StdOutAlerter` was being passed as an argument to `poker.BlindAlerterFunc` and then somehow returning a `BlindAlerter` interface to satisfy the `NewGame()` / `NewTexasHoldem()` signature.

I think a brief description covering that this is actually casting would be helpful.

**Comment by quii** [comment]
Hey there, sorry for taking so long to look at this, but you know, real life :) 

I'll give this a go. But bear in mind this isn't technically "casting", it's [type conversion](https://go.dev/tour/basics/13)

**Comment by quii** [comment]
@hslabbert Does this clear things up? https://github.com/quii/learn-go-with-tests/commit/b8877f83af758e2298a137c5ea885f5335aa03df

**Comment by quii** [comment]
Happy to re-open if not, but need endorphin hit of an issue being closed.

**Comment by hslabbert** [comment]
> Happy to re-open if not, but need endorphin hit of an issue being closed.

Hah! Totally fair, yea.  Works for me, thanks!
