### ISSUE TITLE
Data race in context chapter

### ISSUE THREAD

**Issue by krmaxwell** [quii/learn-go-with-tests#504]
At the conclusion of the chapter on `context`, the compiler finds a data race. This is in the first gofunction inside `(*SpyStore).Fetch`, specifically in [line 26](https://github.com/quii/learn-go-with-tests/blob/aad7a5b68c9da3bd4d6a9f7c1d67f682da00219c/context/v3/testdoubles.go#L26). I'm not certain how to fix this, however.

**Comment by quii** [comment]
It looks like `t.Log` is not safe to use concurrently. For the sake of simplicity, I'll just remove it, it's not so important.
