### ISSUE TITLE
Issue with Integers chapter

### ISSUE THREAD

**Issue by dodalovic** [quii/learn-go-with-tests#507]
After I write code described in https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/integers#write-the-test-first, 
and run `go test`, I'm getting instead:

```
 my-project git:(master) ✗ go test 
found packages integers (adder_test.go) and main (hello.go) in /home/dodalovic/me/projects/my-project
```

**Comment by quii** [comment]
Put them in different folders. The problem you're having is that you're not allowed more than one package per folder.

**Comment by quii** [comment]
Didn't mean to close, let me know if that clears things up and then we can close :)

**Comment by dodalovic** [comment]
I was thinking that you could shortly & effectively explain the modules as well, before proceeding further with the language?

**Comment by quii** [comment]
At the top of the chapter it says

> Note: Go source files can only have one package per directory, make sure that your files are organised separately. 

And then links to an external resource explaining things. 

Do you think there's any way that could've been improved? I don't really want this book simply repeating what the standard documentation says, it's better just to link to existing resources in these cases I think.

**Comment by dodalovic** [comment]
Yes, maybe you're right, let's close this! Thanks for the clarification
