### ISSUE TITLE
File System

### ISSUE THREAD

**Issue by jedruniu** [quii/learn-go-with-tests#51]
Chapter with examples of how to test code that for example does:
`os.Open('file')`
and all other interactions with FS.

**Comment by quii** [comment]
I was having a think about this earlier today. In the HTTP server chapter we made an `InMemoryPlayerStore`. 

It seems like a good continuation of that would be to then make a `FileSystemStore`, so I may give that a go. 

Do you have any other ideas around this? Any particular things to cover?

**Comment by jedruniu** [comment]
I was also thinking about situation where you want command execution, for instance something like I was doing here: https://github.com/jedruniu/spotify-cli/blob/master/auth.go#L174 as well as situtations where you want to test for `os.Create`

**Comment by hackeryarn** [comment]
Maybe it would be good to have a later chapter with a few implementations of different stores with tests? e.g. `FileSystemStore`, `PostgressStore`, `MongoDbStore`

Just to demonstrate how to work with differences of working with different types of stores in Go.

**Comment by quii** [comment]
What I've decided to do recently is have a section called "Build an application", where the reader gets to build something a bit bigger over the course of some chapters. 

With that I'll iterate on the storage requirements

- In memory
- A simple JSON file
- A "real" database.

**Comment by quii** [comment]
Hello all

Now that https://github.com/quii/learn-go-with-tests/blob/master/io.md is done I am going to close this. Obviously it doesn't cover _all_ file system things, but it can at least serve as a primer. 

If anyone feels there are other parts of the go standard lib that should be covered, please raise a new issue detailing the specific things they'd like to see :)
