### ISSUE TITLE
possible mistake in Math

### ISSUE THREAD

**Issue by vegerot** [quii/learn-go-with-tests#568]
shouldn't the `got` point in https://github.com/quii/learn-go-with-tests/blame/main/math.md#L775 be on the unit circle?

**Comment by ruthmoog** [comment]
A bit late to the conversation but, the unit circle is used to find the degrees the clock-hands point at, and we use trigonometry to find the equation to use to find the points.
It's extrapolated to use in the assembly test, on the SVG clockface (for which we made the assumption "every clock has a centre of (150, 150)").
