### ISSUE TITLE
slice length and capacity

### ISSUE THREAD

**Issue by dgsb** [quii/learn-go-with-tests#577]
In this section https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/arrays-and-slices#write-enough-code-to-make-it-pass-2, it seems there is confusion between a slice capacity and a slice length.

Maybe, various slice allocation could be added to clarify what are those two concepts: `make([]int, 0, 5)` vs `make([]int, 5)`

**Comment by deining** [comment]
With PR #785 merged, this issue should be closed.
