### ISSUE TITLE
Video Lectures?

### ISSUE THREAD

**Issue by hack-parthsharma** [quii/learn-go-with-tests#592]
Any video lectures from your side which is interrelated to this repo would be greatly appreciated !

**Comment by ruthmoog** [comment]
There is a video for the Reading Files chapter if you haven't seen that already @hack-parthsharma  ?

[YouTube: Learn Go with Tests: Reading files](https://www.youtube.com/watch?v=nXts4dEJnkU&t=62s&ab_channel=ChrisJames)

**Comment by hack-parthsharma** [comment]
Thanks @ruthmoog I'll follow up with this
