### ISSUE TITLE
Functional desing

### ISSUE THREAD

**Issue by mujehoxe** [quii/learn-go-with-tests#594]
Are we going to see any functional mindset? because all these reassignments are making me dizzy.

**Comment by mujehoxe** [comment]
Maybe adding some chapters to the end, with tdd of course, and start slowly.

**Comment by mujehoxe** [comment]
Also there is this new techniques called mutation testing, would really make the content richer.

**Comment by quii** [comment]
I don't think it's especially useful for this to teach about functional programming at any great depth.

Generally the rationale for chapters are, they must have at least one of the following qualities:

- Teaches a go language feature
- An example of using a Go package
- TDD, general design considerations. 

Mutation testing isn't really that new, but it could make it in to the book someday.

**Comment by mujehoxe** [comment]
Great.

**Comment by mujehoxe** [comment]
yeah i think its usefull to show if your test suit is good enough, and it helps you with edge cases, after applaying it on the Bitcoin wallet for example gave me this result

```
PASS "/tmp/go-mutesting-3919031739/wallet.go.0" with checksum 57132d799313d4847e07cfdab304014d
--- wallet.go	2022-07-30 22:07:39.665995089 +0100
+++ /tmp/go-mutesting-3919031739/wallet.go.1	2022-07-31 08:12:22.917363025 +0100
@@ -18,7 +18,7 @@
 var ErrInsufficientFunds = errors.New("insufficient funds")
 
 func (w *Wallet) Withdraw(amount Bitcoin) error {
-	if amount > w.balance {
+	if amount >= w.balance {
 		return ErrInsufficientFunds
 	}
 

FAIL "/tmp/go-mutesting-3919031739/wallet.go.1" with checksum 10ecd908110fd1748bed3779d81f76fb
PASS "/tmp/go-mutesting-3919031739/wallet.go.2" with checksum da97c7be3850e8d4c6c2905eace6dafa
PASS "/tmp/go-mutesting-3919031739/wallet.go.3" with checksum 5d320ac1ce9aa28b62aff3776a14f55f
The mutation score is 0.750000 (3 passed, 1 failed, 0 duplicated, 0 skipped, total is 4)
```

and after adding this test

```
	t.Run("withdraw same a funds", func(t *testing.T) {
		wallet := Wallet{balance: 10}

		err := wallet.Withdraw(Bitcoin(10))

		assertNoError(err, t)
		assertBalance(wallet, Bitcoin(0), t)
	})


PASS "/tmp/go-mutesting-1700056213/wallet.go.0" with checksum 57132d799313d4847e07cfdab304014d
PASS "/tmp/go-mutesting-1700056213/wallet.go.1" with checksum 10ecd908110fd1748bed3779d81f76fb
PASS "/tmp/go-mutesting-1700056213/wallet.go.2" with checksum da97c7be3850e8d4c6c2905eace6dafa
PASS "/tmp/go-mutesting-1700056213/wallet.go.3" with checksum 5d320ac1ce9aa28b62aff3776a14f55f
The mutation score is 1.000000 (4 passed, 0 failed, 0 duplicated, 0 skipped, total is 4)
```

**Comment by mujehoxe** [comment]
```
func (d Dictionary) Update(word, definition string) error {
	_, err := d.Search(word)

	switch err {
	case ErrWordNotFound:
		return ErrWordDoesNotExists
	case nil:
		d[word] = definition
	default:
		return err
	}

	return nil
}
```
in this example i am getting
```
 	case nil:
 		d[word] = definition
 	default:
-		return err
+		_ = err
+
 	}
 
 	return nil
```
how can i add a test where the search function gives another type of error?

**Comment by mujehoxe** [comment]
just fixed it by lifting return nil
func (d Dictionary) Update(word, definition string) error {
	_, err := d.Search(word)

	switch err {
	case ErrWordNotFound:
		return ErrWordDoesNotExists
	case nil:
		d[word] = definition
		return nil
	default:
		return err
	}
}
