### ISSUE TITLE
Language Fix in Arrays Section

### ISSUE THREAD

**Issue by sdbedi** [quii/learn-go-with-tests#613]
The Arrays section contains the following paragraph:
`Oh no! It's important to note the test has compiled, it is a runtime error.`
[https://github.com/quii/learn-go-with-tests/blob/main/arrays-and-slices.md#try-and-run-the-test-3](url)

It would probably read better as:
`Oh no! It's important to note that while the test has compiled, it has a runtime error.`

**Comment by nikitakoselev** [comment]
The more specific location: 
https://vscode.dev/github/nikitakoselev/learn-go-with-tests/blob/2f268ca8dae8989668e8d56a855e3a050cdcb4cf/arrays-and-slices.md#L483-L485

![image](https://user-images.githubusercontent.com/6383738/197889925-7fc00461-35ee-4d3d-a9ab-527e237ddb58.png)
