### ISSUE TITLE
Mention reflect.TypeOf to avoid duplicaiton of struct names in "Structs, methods & interfaces"

### ISSUE THREAD

**Issue by alexbozhenko** [quii/learn-go-with-tests#614]
The name of the struct and name of the test is duplicated here:
https://github.com/quii/learn-go-with-tests/blob/eb171dcf3d10c009371af7181d8dc7e45b1f51f9/structs/v8/shapes_test.go#L24-L30

@quii Do you think it is worth mentioning that duplication can be avoided with the following?
`t.Run(reflect.TypeOf(tt.shape).Name(), func(t *testing.T) {`
I can submit a PR if you think it is worth adding here.
Thanks!

**Comment by quii** [comment]
Hey, it's not a bad idea but I'd say no. The reason is, this is quite a big chapter in itself so for the purposes of concision, I'd rather leave reflection out of it.
