### ISSUE TITLE
hello world: using a constant has no performance impact

### ISSUE THREAD

**Issue by djlondon** [quii/learn-go-with-tests#631]
The comment about performance in https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/hello-world#constants is misleading. After a writing and running a very simple benchmark, you can see that there is no performance improvement from extracting the string into a constant, in fact the assembly code is the same (https://godbolt.org/z/zfj9oTsTT):
```
        MOVL    $7, CX
        MOVQ    AX, DI
        MOVQ    BX, SI
        XORL    AX, AX
        LEAQ    go.string."Hello, "(SB), BX
        PCDATA  $1, $1
        CALL    runtime.concatstring2(SB)
        MOVQ    40(SP), BP
        ADDQ    $48, SP
        RET
```

My point here is not to be pedantic, but to say that it is misleading to suggest that using a constant here provides *any* performance gains.

**Comment by quii** [comment]
Feel free to raise a PR to remove the comment so you can get some internet points :) Otherwise I'll find some time next week
