### ISSUE TITLE
Optional dark theme

### ISSUE THREAD

**Issue by mbtamuli** [quii/learn-go-with-tests#658]
Would love it if there was a way to select a dark mode.

**Comment by mbtamuli** [comment]
Looks like GitBook has an option to enable Dark Theme for published content - https://docs.gitbook.com/publishing/customization/space-customization#select-dark-or-light-theme-for-published-content. 

But they don't allow to make it configurable when viewing the content. 😞 

Currently I'm using this extension [Dark Mode for Chrome](https://chrome.google.com/webstore/detail/dark-mode/dmghijelimhndkbmpgbldicpogfkceaj/related?hl=en)

**Comment by quii** [comment]
You can download the ebooks and use your favourite e-reader to use dark mode if you wish. Or just read the markdown on github too.

**Comment by sadn1ck** [comment]
Adding a toggle seems to be supported now - https://changelog.gitbook.com/may-2023/30-may-a-light-dark-mode-toggle-and-new-customization-options#new

Would be great if it could be added!

**Comment by fabiomontefuscolo** [comment]
Some companies block everything, including access to extensions. They just don't block our migraine 😢. The dark mode would really help some old eyes get along with this awesome book 🤗.
