### ISSUE TITLE
Should mocking chapter have tests for Sleeper implementation?

### ISSUE THREAD

**Issue by hackeryarn** [quii/learn-go-with-tests#66]
In my opinion, I think that the `Sleeper` implementation test would be very helpful here.  However, I am not sure how this would be done in a nice way.

I would love to help with this if I can get just a little guidance on how to handle this in an idiomatic Go way.

**Comment by quii** [comment]
I'll put some thoughts, if you think they're helpful we can edit them in :) 

```go
type ConfigurableSleeper struct {
    duration time.Duration
}
​
func (o *ConfigurableSleeper) Sleep() {
    time.Sleep(o.duration)
}
```

So we want to test this? Well we dont *really* want to try and measure how long it's sleeping. The only logic we have is that we should call `time.Sleep` for a given duration. So we can inject in a function that mocks `time.Sleep` and then we can record what was sent in.

Something like 

```go 
type SpyTime struct {
   durationSlept time.Duration
}

func (s *SpyTime) Sleep(duration time.Duration) {
   s.durationSlept = duration
}
```

We'll need a way to pass in a sleepy thing into our `Sleeper`

```go
type ConfigurableSleeper struct {
    duration time.Duration
    sleep func(time.Duration)
}
```

In our test we'll pass in our `SpyTime.Sleep` as the sleep function

```go
spyTime := &SpyTime{}
sleeper := ConfigurableSleeper(5 * time.Seconds, spyTime.Sleep)
sleeper.Sleep()

if spyTime.durationSlepy != 5 *time.Seconds {
   // fail
}
```

Does that make sense?

**Comment by hackeryarn** [comment]
Yes it does and that is a very helpful explanation!

**Comment by quii** [comment]
Ok so you mentioned you wanted to get on the coveted contributors list. Do you want to give it a go adding it to the chapter in a PR? Otherwise I'll put something in at a later date.

**Comment by hackeryarn** [comment]
@quii I will get PR submitted this weekend, thanks for the encouragement 😄
