### ISSUE TITLE
Select lesson clarity about defer and test execution

### ISSUE THREAD

**Issue by mud5150** [quii/learn-go-with-tests#679]
In the select lesson, it might be worth pointing out that `defer slowServer.Close()` in `TestRacer()` will take as long as the longest timeout. This is eluded to, but I immediately thought I had done something wrong since the test blocked for the amount of time of the slowest http response. On the upside, it was a good learning experience to figure it out. 

P.S. These lessons are great. Thanks for putting this together.

**Comment by quii** [comment]
I'm not sure what I'd write here. As you say, it explains that defer will run the deferred function when the function ends, in this case, when the test finishes. As you say, readers _should_ be able to infer this. 

(ps, thanks for the kind words)
