### ISSUE TITLE
Need fix: double quotes on switch-case in "Hello, World" lesson.

### ISSUE THREAD

**Issue by Dhar01** [quii/learn-go-with-tests#680]
I'm not sure if it's intentional or not, but there's a double quote on case matching. It's on the **SWITCH** section. 
Shown in the screenshot below:

![image](https://github.com/quii/learn-go-with-tests/assets/25137893/c8fcdeea-b73e-48b8-93db-53727b938b18)

Also, this is my first time opening issues, apology if this doesn't maintain the guideline.

**Comment by anjali29singh** [comment]
It double quote is necessary for strings, otherwise it will give error

**Comment by cyjeffk** [comment]
> I'm not sure if it's intentional or not, but there's a double quote on case matching. It's on the **SWITCH** section. Shown in the screenshot below:
> 
> ![image](https://user-images.githubusercontent.com/25137893/247203988-c8fcdeea-b73e-48b8-93db-53727b938b18.png)
> 
> Also, this is my first time opening issues, apology if this doesn't maintain the guideline.

I was going to add the same issue last week, and OP beat me to it! I confirm OP's point, i.e. in this program _french_ and _spanish_ are the **names** of two string constants, whose values are "French" and "Spanish", respectively.
For the test to pass, I have to either use _french_ and _spanish_, i.e., without quotes, or string literals "French" and "Spanish" as the switch cases, but not "french" and "spanish".

**Comment by quii** [comment]
Sorry all, the intention is you have constants named `spanish` and `french`, which you then use in the switch

**Comment by ruthmoog** [comment]
This will be fixed by @eklmv 's PR https://github.com/quii/learn-go-with-tests/pull/671
