### ISSUE TITLE
Chapter iteration benchmark

### ISSUE THREAD

**Issue by WaDelma** [quii/learn-go-with-tests#694]
Currently the benchmark shown there doesn't assign the return value of `Repeat` anywhere. This means that it could get optimized away and we'd get useless benchmark results.

There should be at least warning about this or the example should be modified so that such optimization cannot happen. [Here](https://stackoverflow.com/questions/36966947/do-go-testing-b-benchmarks-prevent-unwanted-optimizations/36975497#36975497) is an example how this can apparently be done.

**Comment by quii** [comment]
Today I learned! It would be good if someone could add a note about this

**Comment by deining** [comment]
With PR #781 merged, this issue should be closed.
