### ISSUE TITLE
Error in `it records wins on POST` test 

### ISSUE THREAD

**Issue by hackeryarn** [quii/learn-go-with-tests#71]
The test condition `len(store.winCalls) != 1` will always return `False` because of the previous test also recording a win. 

The `store` should ideally be reset for every test to avoid making the tests dependent on each other.

**Comment by quii** [comment]
Could you point to the code?

**Comment by hackeryarn** [comment]
My apology, I was following the directions and missed that we replaced one of the tests. Maybe it would be good to call out the replacement of `it returns accepted on POST` with `it records wins when POST`. I still had both the tests in my session which was causing the issue.

**Comment by quii** [comment]
I'll see if i can get around to re-wording it later 👍

**Comment by quii** [comment]
I just had a re-read, it says just before the next test 

> Now extend our test to check the number of invocations for a start

I think it's fair to say this is telling the reader that we're replacing (extending) the existing test no?
