### ISSUE TITLE
Question for Chapter "Hello, World" 

### ISSUE THREAD

**Issue by upgradeksh** [quii/learn-go-with-tests#718]
Hi there, 
First of all, I really appreciate for this awesome learning course.
I've just read the Chapter, Hello World, can I have a question?

Q) it defined the consts in `hello.go`, spanish, french and englishHelloPrefix, but they aren't used in `hello_test.go`

**Comment by ram-ks** [comment]
You can use declared constants in `hello_test.go` too. It will work. 

```
t.Run("saying hello to people in spanish", func(t *testing.T) {
		want := "Hola, amigo."
		got := Hello("amigo", spanish)
		assertCorrectMessage(t, got, want)
	})
```
