### ISSUE TITLE
We would like to translate the project into Chinese

### ISSUE THREAD

**Issue by polaris1119** [quii/learn-go-with-tests#73]
Hello, I'm a gopher, I founded the Go Chinese community https://studygolang.com in 2013. In order to better promote the go language, the introduction of foreign excellent information to China, in November 2017, I organized the GCTT (Go Chinese Translation Team). 2 months ago, I saw your articles about TDD, and GCTT start translating, and later discovered https://github.com/quii/learn-go-with-tests this project, thanks for providing such a good project, GCTT wants to translate it into Chinese, I wonder if we can do that? Looking forward to your reply. Thank you!

**Comment by pityonline** [comment]
@quii I’m wondering, too! I think it’s great to introduce the project to Chinese gophers!

@polaris1119 if it’s permitted, can I join in?

**Comment by polaris1119** [comment]
@pityonline Sure! Welcome!

**Comment by pityonline** [comment]
@quii This project is kind of technical book with some articles, and it's published on https://quii.gitbook.io/learn-go-with-tests independently. In my opinion, I think the translations could be also independent, but every translation(with URL) should be mentioned in README.md, or a page in the book, like Chinese, French, Russian, etc. Here's an example of [A Tour of Go](https://tour.golang.org/welcome/2). What do you think of it?

@polaris1119 What's your plan? Do you have a better one?

**Comment by polaris1119** [comment]
I agree with @pityonline. We fork the project, the translation of the articles are placed in a separate document, after all, the articles change less.

**Comment by quii** [comment]
Cool!

I'd be happy to include a link to your fork on the English version. If you end up hosting it outsiide of github i'd appreciate it if you link to the original project just so I can maintain some credit.

Other than that I'd love to help you any way I can, although I dont speak any Chinese :)

Good luck and keep in touch

**Comment by quii** [comment]
Hey @polaris1119 @pityonline - just a quick note! I notice you're starting to work on the second section. Just be aware that if a chapter has "WIP" in the name that means it is _work in progress_. As such it is subject to fairly large changes so perhaps hold off on translating those ones 😸

**Comment by pityonline** [comment]
@quii Thank you for your kindly reminder. Don't worry, the **BUILD AN APPLICATION** part is started to translate, but the *WIP* or *TODO* chapters won't be translated until they are *DONE*. cc @polaris1119  @Donng @flw-cn

**Comment by polaris1119** [comment]
@quii Thank you.

**Comment by quii** [comment]
Hello @polaris1119 and @pityonline 

I'm still really proud that you all decided to translate this into Chinese, thanks a lot. 

From my end, I don't think there's anything left to do in respect to supporting your efforts so I'm going to close this issue
