### ISSUE TITLE
Dealing with slow goroutines while using channels

### ISSUE THREAD

**Issue by swamisriman** [quii/learn-go-with-tests#734]
[Here](https://github.com/quii/learn-go-with-tests/blob/main/concurrency.md?plain=1#L441), it is not explained how we are dealing with late goroutines, which was a problem for us [here](https://github.com/quii/learn-go-with-tests/blob/main/concurrency.md?plain=1#L218).

ie; What if we took a very long time to check one of the websites? What if the for loop runs before that's done? How is it taken care of?

PS: I don't know the answer to this (I'm still learning). I'm hoping someone will add this info.

**Comment by quii** [comment]
It's in the next chapter :) https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/select#slow-tests

**Comment by swamisriman** [comment]
Oh ok
I didn't start reading that one yet.
Thanks 😅
