### ISSUE TITLE
formatting the code chunks within the .md file

### ISSUE THREAD

**Issue by UponTheSky** [quii/learn-go-with-tests#748]
Recently I made a PR which has been merged now: #744 

This PR made changes in the code chunks in the .md file, which are demarcated with triple backticks(`)

<img width="882" alt="Screenshot 2024-03-20 at 10 12 44 AM" src="https://github.com/quii/learn-go-with-tests/assets/89925675/3cf56864-9cd5-4d6d-a3e7-e2d9348c0269">

But when I revisit the section in which I made the changes, the rendered code is [like this](https://quii.gitbook.io/learn-go-with-tests/testing-fundamentals/intro-to-acceptance-tests#graceful-shutdown-package):

<img width="954" alt="Screenshot 2024-03-20 at 10 20 50 AM" src="https://github.com/quii/learn-go-with-tests/assets/89925675/d423ba61-8a3c-476c-afca-b3fca1cc7d3f">

This is what I have never expected. It is basically my fault not running `./build.sh` before making PR. I am sorry for making this nuisance. I will make another PR for fixing this.

**Comment by quii** [comment]
To be fair, i should've checked too :) 

Thanks for your contributions, no need for apologies

**Comment by UponTheSky** [comment]
Thank you for your kind reply! Truly enjoying your work 👍
