### ISSUE TITLE
Incorrect Command in README for Launching Go Documentation Locally

### ISSUE THREAD

**Issue by Beka188** [quii/learn-go-with-tests#768]
# godoc -http:8000
I noticed that the README file contains an incorrect command for launching the Go documentation locally. The command provided is ```godoc -http:8000```, but I guess it should be ```godoc -http=:8000```.

The location:
https://github.com/quii/learn-go-with-tests/blob/main/hello-world.md 

This paragraph:
`Go doc
Another quality-of-life feature of Go is the documentation. You can launch the docs locally by running godoc -http:8000. If you go to [localhost:8000/pkg](http://localhost:8000/pkg), you will see all the packages installed on your system.
`

P.S. I am doing this first time, so if i did something wrong, please leave feedback! Thanks in advance.

**Comment by quii** [comment]
It seems this got fixed. This is what it currently states

```
Another quality-of-life feature of Go is the documentation. You can launch the docs locally by running `godoc -http=localhost:8000`. If you go to [localhost:8000/pkg](http://localhost:8000/pkg), you will see all the packages installed on your system.
```
