### ISSUE TITLE
fmt.Println error in pointers-and-errors.md

### ISSUE THREAD

**Issue by Jay54520** [quii/learn-go-with-tests#77]
There are two `fmt.Println`s in  [pointers-and-errors.md](https://github.com/quii/learn-go-with-tests/blob/master/pointers-and-errors.md):

* `fmt.Println("address of balance in test is %v \n", &wallet.balance)`
* `fmt.Println("address of balance in Deposit is %v \n", &w.balance)`

will raise `Println call has possible formatting directive %v`.

Solution is to update to `fmt.Printf`: `fmt.Printf("address of blance in test is %v \n", &wallet.balance)`

**Comment by pityonline** [comment]
@Jay54520 I think it's brought from #76, and I couldn't find any `fmt.Println` in the entire directory of `pointers/`. If you like, feel free to submit a PR. :)

**Comment by quii** [comment]
Good spot, i think i was a bit lazy checking that last PR over!
