### ISSUE TITLE
Integers - package not visible in godoc

### ISSUE THREAD

**Issue by NikolausC** [quii/learn-go-with-tests#779]
I've got to the end of the "Integers" chapter, but I'm not able to get the package to show up when browsing the godoc. I'm using go1.22.4 darwin/amd64. I've tried running the godoc command (`godoc -http=:6060`) from both the chapter directory, and project root. I've searched around, which has lead to me trying prepending the command with `GO111MODULE=off` (no change), and a few different values of the `-goroot` parameter (this lead to `cannot find package "." in: /src`).

Have you any ideas what I'm missing?

Thanks for this project 🙏 

### Tests
```
go test -v
=== RUN   TestAdder
--- PASS: TestAdder (0.00s)
=== RUN   ExampleAdd
--- PASS: ExampleAdd (0.00s)
PASS
ok      hello/integers  0.265s
```

### Project Structure
```
go.mod

hello_world:
hello.go      hello_test.go

integers:
adder.go      adder_test.go
```

**Comment by brandon-carlisle** [comment]
Mine does show in the Standard library section called "go-with-tests". I did assume it would show in the Other packages section.

**Comment by NikolausC** [comment]
So it is. I too thought it would've showed up in "other packages". Thanks!
