### ISSUE TITLE
Proposal: Adding Multilingual Support, Repository Restructuring, and Community Organization

### ISSUE THREAD

**Issue by blackdreamer15** [quii/learn-go-with-tests#804]
Hi @quii!

First and foremost, thank you for creating and maintaining the `Learn Go with Tests` project. It's been a valuable resource for many, myself included.

### Proposal

I’d like to suggest a few initiatives to support and enhance the multilingual aspect of the project:

### Creating a docs Folder

Inside docs, we can have subdirectories for each language (e.g., en for English, fr for French, sp for Spanish, etc.). This would centralize all translations in one place, making it easier to manage and contribute. This would also mean updating the `contributing.md` guidelines.

### Tracking Translation Updates

Implementing a system to monitor changes in the original English content. This could involve automated notifications or badges to indicate when a translation is outdated. The goal is to ensure that translations remain consistent with the original text.

### Community Organization

I’ve noticed that some contributors have already translated parts of the book into other languages and deployed them independently. To bring everyone together, I propose creating a Discord community where we can collaborate more effectively, discuss updates, and coordinate contributions.

### My Contribution
I’m particularly interested in starting the French translation and would be happy to lead this restructuring effort and community organization. I’d also like to reach out to existing translators to invite them to join this community.

Before moving forward, I wanted to get your thoughts on these ideas. If you’re open to them, I can start working on the changes and help set up the community.

Looking forward to hearing your feedback!

Best regards!

**Comment by quii** [comment]
Hi

Thanks for reaching out. I guess my concern is, for better or worse, what exists currently works and doesn't require a central governance function, which appeals to me. Some of the translations are kept more up to date than others, and that's down to the sub communities that run them. As far as I can tell, the Portuguese translation works hard to keep things up to date, and it has its own processes to make that happen. 

My preference therefore is to keep the decentralised approach. Of course, you can make a discord server to _try_ and gather everyone together, although I am a little skeptical on how much uptake you'll get in truth. I'd prefer to keep the current structure, where I add links to the translations as they become published

Thanks for reaching out though! Of course I'd welcome a French translation :)

**Comment by blackdreamer15** [comment]
Hi.

Thank you for the feedback. As such, considering the decentralized structure, I will proceed with the French translation.

Thanks.
